CI on Github Actions
jdi-testing/jdi-light pull request #2787
Opened 2021-02-19 12:54 UTC by pnatashap

CI is created
Performance tests were changed to fail on reduce performance
Test's improvements

2021-02-20 06:40 UTC, alexarm requested changes

2021-02-20 10:16 UTC, pnatashap commented on jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
> +    public static final ILogger logger = instance("JDI");
fixed

2021-02-20 10:16 UTC, pnatashap commented on jdi-light/src/main/java/com/epam/jdi/light/elements/complex/table/Grid.java
> +    public UIElement coreUI() {
core() is available before page is opened. 
Sometimes we need to change default header locator, but this can be changed only when it's visible

2021-02-20 10:18 UTC, pnatashap commented on jdi-light/src/main/java/com/epam/jdi/light/driver/get/DriverData.java
> +    public static void setupChomeCapability(ChromeOptions cap, String property, String value) {
fixed

2021-02-24 07:08 UTC, alexarm commented on jdi-light/src/main/java/com/epam/jdi/light/elements/complex/table/Grid.java
> +    public UIElement coreUI() {
Okay. Fine by me.

2021-02-24 10:04 UTC, alexarm approved these changes

2021-02-28 01:48 UTC, merged