FAST_SEARCH flag is created to do not filter if we get one element
jdi-testing/jdi-light pull request #2823
Opened 2021-03-11 16:47 UTC by pnatashap

2021-03-18 11:07 UTC, RomanIovlev requested changes
Please fix comments
1. Do not touch already existing tests (if they fail because of new logic, better to set proper settings for them instead of changing tests)
2. Replace two variables STRICT, FAST search with one SEARCH_STRATEGY that have 3 + 1(DEFAULT) values 
3. update property reader based on point 2
4. Make method for filtering results more clear, based on the selected strategy

2021-03-18 11:07 UTC, RomanIovlev commented on jdi-light/src/main/java/com/epam/jdi/light/elements/base/JdiSettings.java
>      public static WebElement filterWebListToWebElement(JDIBase base, List<WebElement> els) {
decisions becomes to complex, so better to change this code to something like this:
```
public static WebElement filterWebListToWebElement(JDIBase base, List<WebElement> els) {
	if (els.isEmpty())
		throw exception(FAILED_TO_FIND_ELEMENT_MESSAGE, base.toString(), base.getTimeout());
	SearchType searchType = base.searchType == DEFAULT ? SEARCH_TYPE : base.searchType;
	switch (searchType) {
		case(SOFT):
			return softSearch(base, els);
		case(FAST):
			return fastSearch(base, els);
		case(STRICT):
			return strictSearch(base, els);
		default:
			throw exception("Unknown search type");
	}
}
```

2021-03-18 11:07 UTC, RomanIovlev commented on jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
> +                FAST_SEARCH = false;
please revert this back

2021-03-18 11:07 UTC, RomanIovlev commented on jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
> +                FAST_SEARCH = false;
please revert this back

2021-03-18 11:07 UTC, RomanIovlev commented on jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
> +                FAST_SEARCH = false;
please revert this back

2021-03-18 11:07 UTC, RomanIovlev commented on jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
> +            if (params.contains("fast"))
this should be one variable with 3 possible values

2021-03-19 08:12 UTC, pnatashap commented on jdi-light-bootstrap-tests/src/test/java/io/github/epam/bootstrap/tests/complex/CarouselTests.java
> +		info.is().hidden();
This slide is not visible, so we can't get any information about it in case of STRICT strategy

2021-03-19 08:19 UTC, pnatashap commented on jdi-light-html/src/main/java/com/epam/jdi/light/ui/html/elements/common/Checkbox.java
> +        base().noValidation();
Yes, it's connected to the issue: Checkbox often is not visible itself and used only as a data container and in this case it's invisible 100% time (overlaped by nice div), but we need to work with using ALL strategies.

2021-03-19 08:21 UTC, pnatashap commented on jdi-light-html-tests/src/test/java/io/github/epam/html/tests/elements/complex/list/ElementsGoogleTests.java
> +        searchPage.search.assertThat().displayed();
This is only a wait that the page is loaded. Good step in any case.

2021-04-06 11:18 UTC, merged