Add deletableChipTest and selectedListTest to MaterialUI module
jdi-testing/jdi-light pull request #3017
Opened 2021-07-15 15:23 UTC by mikhnovich

- add lastDeleteInfo element to chipsPage
- add deleteChipTest to ChipTests class
- add inputSelectedListItem, trashSelectedListItem to ListPage
- add selectedList to ListsTests class

2021-07-15 17:37 UTC, cold-flame approved these changes

2021-07-19 09:01 UTC, cold-flame requested changes

2021-07-19 09:14 UTC, mikhnovich commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/ListPage.java
> +    public List<UIElement> secondaryLineListItems;
поменяла

2021-07-19 09:27 UTC, cold-flame approved these changes

2021-07-19 09:28 UTC, merged