Master material UI
jdi-testing/jdi-light pull request #3117
Opened 2021-07-22 11:31 UTC by IgorGaidukEpam

2021-08-05 09:44 UTC, pnatashap requested changes
ИСПРАВЛЯТЬ!

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/PaperPage.java
> +    public static List<UIElement> paper;
а точно List< UIElement > должен быть? нет для спец компонента?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/utils/PopperPage.java
> +    public static UIElement tooltip;
а точно UIElement  должен быть? нет для спец компонента?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/utils/TransitionPage.java
> +    public static List<UIElement> collapseFadeTransitions;
а точно List< UIElement > должен быть? нет для спец компонента? (к трем строкам вопрос)

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/TestsInit.java
> +        killAllSeleniumDrivers();
нельзя этого делать в setUp, а если что-то выполняется?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/BadgeTests.java
> +        badge.get(1).is().displayed();
оба badge имеют id. как обо используется - очень странно.

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/BadgeTests.java
> +        badgeCounter.get(1).is().text("4");
Исходное описание компонента такое: 
<Badge badgeContent={4} color="error">
  <MailIcon />
</Badge>
Почему не сделать нормальный доступ к тексту? Понятно, что можно вот так просто, но выглядит очень странно

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
> +    @BeforeMethod
тесты надо переписывать, но пока не до этого, но вообще надо перепроверять, что там делается

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/ButtonGroupAssert.java
> +
а точно нужен, если пустой?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/ButtonAssert.java
> +public class ButtonAssert extends UIAssert<ButtonAssert, Button> {
очень странное положение, если этот assert полезен, нужно его в jdi-light добавлять, странно будет, что он в этом пакете

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/feedback/ProgressAssert.java
> +    @JDIAction(value = "Get '{name}' value '{0}'")
некорректное описание

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SelectAssert.java
> +
точно нужен

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SliderAssert.java
> +  @JDIAction("Assert that '{name}' volume {0}")
причем тут volume ?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SliderRangeAssert.java
> +
пустые строки удаляем

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SliderRangeAssert.java
> +  @JDIAction("Assert that orientation is '{name}'")
Assert that orientation is '{0}'

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/BottomNavigationAssert.java
> +    @JDIAction("Assert that '{name}' is disabled")
неправильное значение в описании

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +        this.getChipLabel(index).click();
какой такой индекс? 
https://material-ui.com/components/chips/ (там можно исходники посмотреть, отдельная кнопочка - отдельный chip

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Button.java
> +public class Button extends UIBaseElement<ButtonAssert> {
в чем отличие этой кнопки от базовой кнопки в jdi-light?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/ButtonWithTooltip.java
> +
а почему пусто?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Checkbox.java
> +public class Checkbox extends UIBaseElement<CheckboxAssert>{
в чем отличие от базового checkbox?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Select.java
> +public class Select extends UIBaseElement<SelectAssert> {
вроде есть базовый контрол такой. или чего-то нехватило?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +public class TextField extends UIBaseElement<TextFieldAssert> {
в чем отличия от базового?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/StringUtils.java
> +        char[] password = new char[r.nextBoolean()?12:13];
странное имя password

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/enums/CurrencyItems.java
> +  USD("$"),
а почему вдруг такой список короткий?

2021-08-05 09:44 UTC, pnatashap commented on jdi-light-mobile/src/main/java/com/epam/jdi/light/mobile/CoordinateConversionHelper.java
>      public static Point getCoordinatesInViewport(int x, int y) {
удалить все изменения пакета mobile

2021-08-05 09:44 UTC, pnatashap commented on jdi-light/src/main/java/com/epam/jdi/light/driver/WebDriverUtils.java
> +			default: break;
выглядит как-будто форматирование поехало

2021-08-05 09:44 UTC, pnatashap commented on jdi-light/src/main/java/com/epam/jdi/light/elements/common/UIElement.java
> +    public void clear() {
нужно описать обоснование необходимости так делать. выглядит как-будто это надо параметризовывать

2021-08-05 09:44 UTC, pnatashap commented on jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
> +        localP = localP.toLowerCase();
а почему 317 и 318 не объединить в одну сразу?

2021-08-11 09:41 UTC, tsvetaevAlex commented on jdi-light/src/main/java/com/epam/jdi/light/settings/WebSettings.java
> +        localP = localP.toLowerCase();
> 
> 
> а почему 317 и 318 не объединить в одну сразу?

pattern: avoid reassigning parameters
solution: use local variables

2021-08-17 06:56 UTC, daxdue commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Checkbox.java
> +public class Checkbox extends UIBaseElement<CheckboxAssert>{
Ассерт базового checkbox не позволяет проверить состояние checked/unchecked

2021-08-22 20:34 UTC, Flowina commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/navigation/BreadcrumbsPage.java
> +    public static List<UIElement> icons;
Исправлено в [#3205](https://github.com/jdi-testing/jdi-light/issues/3205)

2021-08-22 20:45 UTC, Flowina commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/navigation/BreadcrumbsPage.java
> +    public static UIElement coreElement;
исправлено в [#3205](https://github.com/jdi-testing/jdi-light/issues/3205)

2021-08-30 10:48 UTC, Liliya-web commented on jdi-light-material-ui-tests/src/main/java/io/github/com/StaticSite.java
> +    public static DrawerPage swipeableDrawerPage;
Я правильно понимаю, что не должно быть нескольких переменных типа DrawerPage? Нежно сделать элементы других типов, которые экстендят DrawerPage?

2021-08-30 13:10 UTC, Liliya-web commented on jdi-light-material-ui-tests/src/main/java/io/github/com/StaticSite.java
> +    public static WebPage bottomAppBarPage;
Я правильно понимаю, что, во-первых, нужно заменить WebPage на более конкретный тип, который экстендит WebPage, и написать тесты на эти элементы и на те, которые отмеченны такими же комментариями ниже?

2021-08-30 15:18 UTC, Liliya-web commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/AvatarPage.java
> +    public static List<UIElement> onlineStatus;
В package io.github.com.custom есть класс Avatar, который наследуется от секции, но этот класс для наших целей не подходит, потому что у него есть поля Image image, Text description и Checkbox vip. Нам из этого нужно, как максимум, картинка. И то, если заменить UIElement на Image, придется придумывать другие проверки и я пока не знаю как их реализовать. Пыталась заменить для фото UIElement на Image и onlineStatus на Icon, тогда в тестах появляются методы, которые неприменимы к этим элементам. В итоге оставила везде List<UIElement>. Только сделала для аватара с картинкой вложенный класс, который наследуется от секции и расположен на AvatarPage и немного порефакторила тесты, но по смыслу они остались примерно такими же

2021-08-30 16:03 UTC, Liliya-web commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/feedback/BackdropPage.java
> +    public static UIElement backdrop;
Кажется, нет ничего подходящего

2021-09-01 04:58 UTC, Liliya-web commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/ButtonGroupAssert.java
> +
Убрать этот класс, получается, и использовать вместо него простой UIAssert?

2021-09-01 05:15 UTC, Liliya-web commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/ButtonAssert.java
> +public class ButtonAssert extends UIAssert<ButtonAssert, Button> {
Перекопировала ассерты в новый класс ButtonAssert в jdi-light-html. В material-ui они тоже остались

2021-09-01 10:18 UTC, pnatashap requested changes
заберите последнюю версию master

2021-09-01 10:18 UTC, pnatashap commented on jdi-light-material-ui-tests/pom.xml
> +            <artifactId>jdi-light-html</artifactId>
этот модуль должен быть ипортирован в jdi-light-material-uiЮ дополнительно его импортировать не нужно

2021-09-01 10:18 UTC, pnatashap commented on jdi-light-material-ui-tests/pom.xml
> +        <jdi.version>1.3.13</jdi.version>
притяните последнюю версию master, там уже 14 версия

2021-09-01 10:18 UTC, pnatashap commented on jdi-light-material-ui/pom.xml
> +    <version>1.3.13</version>
подтяните последнюю версию master, там 14 версия

2021-09-01 10:18 UTC, pnatashap commented on jdi-light-material-ui/pom.xml
> +            <artifactId>jdi-light</artifactId>
как и в других модулях библиотек, скорее всего должен быть импорт light-html

2021-10-01 18:39 UTC, pnatashap requested changes
Все элементы надо переописывать.
Вот пример из html описаний, создается ощущение, что специально сделано не так
https://github.com/jdi-testing/jdi-light/blob/master/jdi-light-html/src/main/java/com/epam/jdi/light/ui/html/elements/common/Image.java

2021-10-01 18:39 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/Popper.java
> +    public boolean isPopperDisplayed(){
В UIElement есть метод isDisplayed, с точно такой же реализацией. Этого метода быть не должно

2021-10-01 18:39 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/Popper.java
> +    public String getPopperPosition(){
Текст в JDIAction не соответсвует коду, метод должен быть переименован, имя класса в метода не должно присутствовать, например topPosition 
Почитайте класс UIElement, там очень мало методов get*

2021-10-01 18:39 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/Popper.java
> +    public String getPopperText(){
В UIElement есть метод text(), использовать или его или переопределить

2021-10-01 18:39 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/Popper.java
> +       return core().getAttribute("x-placement");
Есть короткая обертка для получения атрибута attr("x-placement")

2021-10-01 18:39 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/StringUtils.java
> +    public static String generateRandomString() {
к MaterialUI метод не имеет никакого отношения, должен быть перенесен в material-ui-tests

2022-01-21 12:41 UTC, closed without merging