3038 vuetify and vuetify tests modules
jdi-testing/jdi-light pull request #3195
Opened 2021-07-30 15:08 UTC by IgorGaidukEpam

2021-08-05 08:18 UTC, pnatashap requested changes
нужно исправить и еще сразу добавить запуск тестов в Github Actions в файле debug.yml, чтобы сразу проверять, что все работает в CI, а не только локально

2021-08-05 08:18 UTC, pnatashap commented on jdi-light-vuetify-tests/pom.xml
> +    <version>1.3.2</version>
обратите внимание на версию!!! она должна совпадать с версией jdi

2021-08-05 08:18 UTC, pnatashap commented on jdi-light-vuetify-tests/pom.xml
> +        <aspectj.version>1.9.5</aspectj.version>
версия 1.9.5 на некоторых версиях jdk несовместима с используемой в jdi 1.9.6.
ВСЕ библиотеки должны использоваться одинаковой версии

2021-08-05 08:18 UTC, pnatashap commented on jdi-light-vuetify-tests/pom.xml
> +            <version>1.3.2</version>
1. Здесь должна быть текущая версия jdi
2. При использовании нескольких библиотек правильно создавать переменную, в которой хранится версия, они должны меняться синхронно

2021-08-05 08:18 UTC, pnatashap commented on jdi-light-vuetify-tests/pom.xml
> +        <profile>
а почему нет профиля для запуска всех тестов?

2021-08-05 08:18 UTC, pnatashap commented on jdi-light-vuetify/pom.xml
> +    <version>1.3.2</version>
про версию написано выше, тоже исправить

2021-08-05 08:18 UTC, pnatashap commented on jdi-light-vuetify/pom.xml
> +        <aspectj.version>1.9.5</aspectj.version>
перепроверить все комментарии к pom.xml от тестов, они тут тоже применимы

2021-08-05 08:18 UTC, pnatashap commented on jdi-light-vuetify/pom.xml
> +        <allure.testng>2.13.1</allure.testng>
testng не может использоваться в основной библиотеке, зачитстите пожалуйста неиспользуемые переменные

2021-08-05 09:56 UTC, TheFifthMoon commented on jdi-light-vuetify-tests/pom.xml
> +        <profile>
Тут не стал это делать - хотел дождаться, какая сама структура проекта будет, в зависимости от неё добавлять. Но ок, можно сразу.

2021-08-05 09:59 UTC, IgorGaidukEpam commented on jdi-light-vuetify-tests/pom.xml
> +        <profile>
Тут не стал этого делать, хотел дождаться, какая у нас в принципе структура будет тестов. Но ок, можно и сразу добавить.

2021-08-10 10:53 UTC, pnatashap requested changes
в комментариях

2021-08-10 10:53 UTC, pnatashap commented on jdi-light-vuetify-tests/pom.xml
> +    <version>${jdi.version}</version>
здесь не работает переменная

2021-08-10 10:53 UTC, pnatashap commented on jdi-light-vuetify-tests/pom.xml
> +        <profile>
для materail-ui ни один из профилей не работал, надо делать один

2021-08-10 10:53 UTC, pnatashap commented on jdi-light-vuetify-tests/src/main/java/io/github/com/StaticSite.java
> +    public static class User extends DataClass<User> {
это надо вынести из сайта, чтобы никто не копировал больше

2021-08-10 10:53 UTC, pnatashap commented on jdi-light-vuetify/pom.xml
> +    <version>${jdi.version}</version>
не работают тут переменные

2021-08-10 10:53 UTC, pnatashap commented on jdi-light-vuetify/pom.xml
> +            <scope>compile</scope>
думаю, что scope тут не нужен, как и ниже

2021-08-10 10:53 UTC, pnatashap commented on jdi-light-vuetify/pom.xml
> +        <allure.maven>2.10.0</allure.maven>
в основной библиотеке allure врят ли используется

2021-08-12 13:21 UTC, pnatashap approved these changes

2021-08-12 17:50 UTC, merged