3481,3482 implement textfields
jdi-testing/jdi-light pull request #3520
Opened 2021-11-19 08:29 UTC by alexkashin90

2021-11-19 09:10 UTC, pnatashap requested changes
только TextField посмотрела, там комментарии

2021-11-19 09:10 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        getTextArea().clear();
getTextArea() каждый раз будет искать элемент по локатору, ооочень медленно будет, надо его один раз взять и с ним работать.
еще есть CTRL+A и удалить, например clearInputField() можно поискать в коде

2021-11-19 09:10 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        getTextArea().sendKeys(Keys.SPACE);
без комментария не понятно, зачем нам нужен пробел и снова удаление

2021-11-19 09:10 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public String hasAdornmentPosition() {
Этого метода тут не должно быть, только получение списка Adornment и все, положение пусть он сам отдаст. 
Просто не понятно, что тут возвращать, если их два

2021-11-19 09:10 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public String hasAdornmentText() {
Аналогично комментарию выше, удаляем отсюда, текст у adornment спрашивать

2021-11-19 09:10 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        if(find(".MuiInputBase-root").attr("class").contains("multiline")) {
форматирование бы поправить, пробел после if хотя бы

2021-11-19 09:10 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public Adornment adornment() {
Еще надо список уметь возвращать

2021-11-19 09:10 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        public void clickOnAdornment() {
просто click c @Override (в Button он должен быть)

2021-11-19 11:30 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public void sendText(String text) {
в интерфейсе IsText нету методов для воода текста. Заимплементил интерфейс IsInput и заоверрайдил оттуда методы sendKeys и setText

2021-11-19 12:42 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public boolean hasPlaceholder() {
сделал

2021-11-19 12:42 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        } else throw exception("Text Field does not have helper text");
Сделал интрефейс, в случае, если элемента нет, метод теперь возвращает null

2021-11-19 12:42 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public boolean isFocused() {
сделал

2021-11-19 12:42 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public boolean hasError() {
сделал

2021-11-19 12:43 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public String hasAdornmentPosition() {
перенес в adornment

2021-11-19 12:44 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public String hasAdornmentText() {
перенес в Adornmen

2021-11-19 12:44 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        if(find(".MuiInputBase-root").attr("class").contains("multiline")) {
поправил

2021-11-19 12:44 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +    public Adornment adornment() {
добавил метод adornments

2021-11-19 12:45 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        public void clickOnAdornment() {
заоверрайдил метод click() в классе Adornment

2021-11-19 12:50 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        getTextArea().clear();
изменил метод по подобию clearInputField()

2021-11-19 15:04 UTC, pnatashap requested changes
Интерфейсы еще поправить

2021-11-19 15:04 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasPlaceholder.java
> +public interface HasPlaceholder extends HasLabel {
Тоже не вижу смысла наследоваться от HasLabel, ICoreElement достаточно.

2021-11-19 15:04 UTC, pnatashap commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasPlaceholder.java
> +    }
Еще бы метод для получения значения, судя по всему без реализации по-умолчанию, они везде разные

2021-11-19 19:05 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +        getTextArea().sendKeys(Keys.SPACE);
удалил это метод по подобию clearInputField() решил проблему

2021-11-19 19:06 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Adornment.java
> +                .collect(Collectors.joining())
изменил метод

2021-11-19 19:06 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/CanBeFocused.java
> +public interface CanBeFocused extends HasLabel {
изменил метод

2021-11-19 19:06 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasErrorNotification.java
> +public interface HasErrorNotification extends HasLabel {
изменил метод и название интерфейса

2021-11-19 19:06 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasErrorNotification.java
> +        return label().attr("class").contains("Mui-error");
изменил метод

2021-11-19 19:06 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasPlaceholder.java
> +public interface HasPlaceholder extends HasLabel {
изменил метод

2021-11-19 19:07 UTC, alexkashin90 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasPlaceholder.java
> +    }
добавил метод без реализации

2021-11-21 22:50 UTC, pnatashap approved these changes

2021-11-26 08:07 UTC, knadonenko approved these changes

2021-11-26 08:07 UTC, merged