Task#3751: fix failed test in Tabs
jdi-testing/jdi-light pull request #3813
Opened 2022-01-30 17:29 UTC by foria1405

- Tests overflowToMenuTabsTest() and dynamicTabsTest() have been fixed.
- remove methods assertThat(), add(), remove() in class VuetifyTabs
- added addButton and removeButton in class TabsPage
- remove OVERFLOW_MENU_DATA in TabsTests
- fixed codacy issue "star imports" in TabsTests

2022-03-21 15:20 UTC, Kratlis requested changes

2022-03-21 15:20 UTC, Kratlis commented on jdi-light-vuetify-tests/src/main/java/io/github/com/pages/TabsPage.java
> +    @UI("//span[contains(text(), 'Remove Tab')]")
Можно упростить локаторы? https://jdi-docs.github.io/jdi-light/#jdi-locators-as-simple-as-css-as-powerful-as-xpath

2022-03-21 15:20 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/TabsTests.java
>          }
Подобные циклы есть и в других тестах. Проверяет ли этот что-то новое? Нужен ли он?

2022-03-21 15:20 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/TabsTests.java
> +        addButton.is().text("ADD TAB");
Проверки можно объединить

2022-03-21 15:23 UTC, Kratlis commented
И в тестах на CI валится dynamicTabsTest

2022-04-27 11:23 UTC, foria1405 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/TabsTests.java
> +        addButton.is().text("ADD TAB");
Объединила

2022-04-27 11:24 UTC, foria1405 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/TabsTests.java
>          }
Постаралась убрать одинаковые проверки и немного поменяла некоторые тесты

2022-04-27 11:24 UTC, foria1405 commented on jdi-light-vuetify-tests/src/main/java/io/github/com/pages/TabsPage.java
> +    @UI("//span[contains(text(), 'Remove Tab')]")
Постаралась упростить

2022-04-27 14:11 UTC, Kratlis commented on jdi-light-vuetify-tests/src/main/java/io/github/com/pages/TabsPage.java
> +    @UI("//span[contains(text(), 'Remove Tab')]")
Сейчас кнопки сделаны как лист. Думаю, лучше сделать как было, отдельными кнопками. Я имела в виду изменить локаторы: `button['Add Tab']`. Типа такого

2022-04-27 14:20 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/TabsTests.java
>          }
Тесты проверит Аня

2022-04-28 09:01 UTC, Kratlis approved these changes

2022-07-16 01:36 UTC, merged