3688 complex.ListsTests assertions
jdi-testing/jdi-light pull request #3835
Opened 2022-02-11 11:43 UTC by stanislavdmitriev-epam

- Introduced a class with assertions
- Sublist expansion declared as a separate method (extracted from sublist() method)
- Refactored tests with new assertions, similar code blocks reworked as loops

2022-02-11 13:42 UTC, Kratlis requested changes
Комментарии по тестам добавлены

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
>      }
Можно удалить?

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
>      }
Можно удалить? (при этом элементы сами не удаляем, нужно всё отображать на странице (в связи с недавними комментариями Наташи))

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
>      }
Насколько я поняла из документации, в этом элементе речь идёт о subtitle. При этом subtitle можно проверить у другого листа в тестах (если есть). Если title проверяется у какого-то другого листа, этот тест можно удалить

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
> +        twoLinesAndSubheaderListSubheader.get(1).is().displayed().and().text("Folders");
В [документации](https://vuetifyjs.com/en/components/lists/#two-lines-and-subheader) subheader является частью листа. Можно ли его добавить в элемент?

И если subheader можно проверить в другом тесте, этот тест можно удалить

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
>      public static void expansionListsListTest() {
Можно ли проверить раскрытие/сжатие листов?

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
> +        }
Title здесь можно не проверять. Он уже проверялся в других

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
>          actionAndItemGroupsListCheckbox.get(2).is().unchecked();
Если возможно, можно попробовать кликать на элементы листа и проверять, что чекбокс выбран

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
>      }
Можно удалить?

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
>      }
Можно удалить

2022-02-11 13:42 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/ListsTests.java
>      }
Можно удалить. У него нет особой функции

2022-02-11 13:45 UTC, Kratlis reviewed
Комментарий по VuetifyList

2022-02-11 13:45 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/VuetifyList.java
> +    }
Переопределение has() необходимо?

2022-02-14 06:40 UTC, stanislavdmitriev-epam commented
Task for updates related to removing similar tests: https://github.com/jdi-testing/jdi-light/issues/3836

2022-02-16 10:01 UTC, NewerNaigil approved these changes

2022-02-16 10:02 UTC, merged