3844 menutest refactoring
jdi-testing/jdi-light pull request #3870
Opened 2022-02-22 12:08 UTC by IvKardapolov

2022-02-24 12:06 UTC, Kratlis requested changes
Дополнительные комментарии:
- нужно ли переопределять `has()` в Menu?
- можно добавить в тестах `show()`

2022-02-24 12:16 UTC, Kratlis requested changes
Reviewed asserts

2022-02-24 12:16 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/MenuAssert.java
> +    @JDIAction("Assert that '{name}' text is '{0}'")
Убрать 'is': Assert that {name} text {0}

2022-02-24 12:16 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/MenuAssert.java
>          return this;
Можно заменить на: `return text(Matchers.is(text));`

2022-02-25 10:34 UTC, Kratlis requested changes

2022-02-25 10:34 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/navigation/ContextMenuPage.java
>      public static Menu contextMenu;
Это не Menu, это текст

2022-02-25 10:34 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/navigation/MenuTests.java
>          contextMenu.isDisplayed();
Использовать MenuAssert

2022-02-25 11:03 UTC, Kratlis approved these changes

2022-02-25 13:42 UTC, NewerNaigil approved these changes

2022-02-25 13:46 UTC, NewerNaigil commented
Пункты описанные в задаче выполнены. Дальнейшие изменения элемента Menu в issue #3875

2022-02-25 13:46 UTC, merged