Material UI: Slider refactoring #3843
jdi-testing/jdi-light pull request #3873
Opened 2022-02-24 12:46 UTC by serafimovmax

Methods refactoring. labelIsVisible() and setAttributes()

2022-05-16 17:56 UTC, annav00 requested changes

2022-05-16 17:56 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/SliderTests.java
> +        slider.is().type(CONTINUOUS);
Если несколько проверок относятся к одному элементу, то через and() их обычно объединяем. 
И для type, attr и подобных проверок, когда элемент имеет какой-то аттрибут, используем не is(), а has().

2022-05-16 17:56 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Slider.java
> + * @see <a href="https://v4.mui.com/components/slider/">List MUI documentation</a>
List вместо Slider

2022-05-16 17:56 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Slider.java
>      }
Здесь не нужно @JDIAction добавить?

2022-05-16 17:56 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/SliderRange.java
> + * @see <a href="https://v4.mui.com/components/slider/#range-slider">List MUI documentation</a>
List вместо Slider

2022-05-16 17:56 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SliderRangeAssert.java
>  public class SliderRangeAssert extends UIAssert<SliderRangeAssert, SliderRange> {
```
/**
 * Assertions for {@link SliderRange}
 */
```

2022-05-16 17:56 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SliderAssert.java
>  public class SliderAssert extends UIAssert<SliderAssert, Slider> {
```
/**
 * Assertions for {@link Slider}
 */
```

2022-05-16 17:56 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/ISlider.java
> +    @JDIAction(value = "Get {name}'s slider label")
"Get {name} slider label", без 's

2022-05-16 17:56 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/ISlider.java
> +        return core().find(By.cssSelector(".MuiSlider-track"));
Можно убрать By.cssSelector?

2022-05-17 07:10 UTC, Kchebulaev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Slider.java
>      }
@JDIAction навешан в ISlider, из которого вызывается thumbs(1)

2022-05-17 16:14 UTC, merged