Switch refactoring
jdi-testing/jdi-light pull request #3878
Opened 2022-03-02 07:59 UTC by kalimullina

**Switch**
- Switch implement HasLabel and override label() method
- Delete isDisabled() and changed isEnabled()
- Deleted getInputColor(), hasLabel(), getLabelText(), getLabelHTML(), hasInputProgressBar()

**SwitchAssert**
- Changed Matchers.is(boolean) for Matchers with ternary operator

**SwitchTests**
- Deleted colorTest(), flatSwitch(), insertSwitch() methods and "forEach(Switch::isDisabled)" construction in each test
- Сreateв basic functionality test with check there css styles -- functionalityAndCssStyleSwitchTest()
- "Test" added to the name of all tests
- Checked loading in statesSwitchTest() 
- Changed labelSwitches on Switch (was list)
- Changed labelSwitchTest() logic
- Create test for model as boolean -- modelAsBooleanSwitchesTest()

2022-03-23 04:01 UTC, Kratlis requested changes

2022-03-23 04:01 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/Switch.java
>      }
Можно использовать core().find("input")?

2022-03-23 04:03 UTC, Kratlis commented
И проверь чекстайлом. Ругался на класс ассертов

2022-03-24 13:40 UTC, Kratlis approved these changes

2022-03-29 07:22 UTC, NewerNaigil approved these changes

2022-03-29 07:23 UTC, merged