Изменил CheckboxTests. Сделал методы чекеры для разного типа чекбоксо…
jdi-testing/jdi-light pull request #3880
Opened 2022-03-03 07:55 UTC by IvKardapolov

…в. Удалил лишнее из дата провайдера. Изменил селекторы в CheckboxPage разбил fromGroupcheckboxes на две коллекции. Добавил проверку на некликабельность в CheckboxAssert

2022-03-03 13:15 UTC, Kratlis requested changes
Были обсуждены идеи упрощения тестов

2022-03-03 13:15 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Checkbox.java
> +    public boolean isEnabled() {
Добавить аннотацию JDIAction

2022-03-05 10:24 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/test/data/CheckboxesDataProvider.java
> +    }
В дата провайдерах можно сразу передавать чекбокс. Пример - MenuTests

2022-03-05 10:24 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/CheckboxTests.java
> +            checkbox.is().checked();
Здесь необходим if-else? Элемент ведь один

2022-03-05 10:24 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/CheckboxTests.java
> +        Checkbox secondCheckbox = mirrorFormGroupCheckboxes.get(secondCheckboxIndex);
Можно убрать переменные для индексов? Они используются только для получения чекбоксов

2022-03-05 10:24 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/CheckboxTests.java
>      @Test()
Можно круглые скобочки убрать

2022-03-05 12:33 UTC, Kratlis approved these changes

2022-03-09 12:37 UTC, NewerNaigil requested changes
Remove all changes with not connected with Checkbox

2022-03-10 13:53 UTC, Kratlis requested changes

2022-03-10 13:53 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/CheckboxTests.java
> +        checkbox.has().iconSize(20, 20);
Icon можно сделать частью чекбокса, используя аннотацию UI?

2022-03-10 13:53 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/CheckboxTests.java
> +        pickTwoText.has().css("color", grey600Cmyk);
Почему используется строка, а не цвет из энама?

2022-03-10 13:53 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Checkbox.java
> -        if (isUnchecked()) {
Лучше использовать isUnchecked. Это читается лучше

2022-03-10 13:53 UTC, Kratlis commented on jdi-light/src/main/java/com/epam/jdi/light/elements/interfaces/base/ICoreElement.java
> +    default boolean isUnchecked() {return  !isChecked();}
Насколько я знаю, мы не можем менять модуль jdi-light

2022-03-10 13:53 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/CheckboxAssert.java
>      public CheckboxAssert disabled() {
Надо переопределять enabled/disabled? Если да, то надо добавить аннотацию Override, если нет - убрать их

2022-03-10 13:53 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/CheckboxAssert.java
> +        jdiAssert(element().isChecked() ? "is checked" : "is unchecked", Matchers.is("is unchecked"));
Вариант до исправления читается лучше

2022-03-10 13:53 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Checkbox.java
> -    }
Лучше оставить этот метод. Кода немного, но можно будет использовать его

2022-03-10 13:53 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Checkbox.java
> +public class Checkbox extends UIBaseElement<CheckboxAssert> implements HasClick, HasLabel, HasColor {
- Стоит переместить метод `label()` в начало класса. В элемента первыми методами должны быть те, которые возвращают элементы
- Проверь текст аннотаций на корректность и соответствие Инструктажу

2022-03-10 13:53 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/CheckboxAssert.java
> +        icon.has().height(height).and().has().width(width);
Добавь текст аннотации и проверь остальные на корректность и соответствие Инструктажу

2022-03-10 14:03 UTC, IvKardapolov commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/CheckboxTests.java
> +        pickTwoText.has().css("color", grey600Cmyk);
Цвет из енама даёт rgba. На странице мы имеем тот же цвет, но в формате cmyk. Как вариант можно перелопатить весь enum для добавляения туда ещё cmyk

2022-03-11 08:52 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/CheckboxTests.java
> +        checkbox.has().iconSize(20, 20);
Можно убрать метод iconSize из ассертов чекбокса и использовать ассерты  Icon

2022-03-11 09:14 UTC, Kratlis approved these changes

2022-03-11 13:18 UTC, NewerNaigil approved these changes

2022-03-11 13:18 UTC, merged