3858 switch tests refactoring
jdi-testing/jdi-light pull request #3889
Opened 2022-03-05 08:00 UTC by annav00

Removed basicSwitchTestLogic
Wrote a test which tests basic logic
Changed names containing turnedOn/turnedOff to checked/unchecked

2022-03-09 12:18 UTC, Kratlis requested changes

2022-03-09 12:18 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/SwitchTests.java
>      }
Здесь тоже можно обойтись без дополнительного метода и дата провайдера. Достаточно проверить начальные состояние и текст, изменить и проверить конечные состояние и текст

2022-03-09 12:18 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +    public boolean isChecked() {
Лучше изменить текст аннотации, чтобы соответствовал шаблону в Инструктаже: "Check that '{name}' is checked"

2022-03-09 12:18 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
Обновить комментарий над классом

2022-03-09 12:18 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
>      }
- из аннотация ниже убрать букву 's'
- перед find использовать core()
- убрать this: this.containsDisabled()
- добавить аннотацию методу `isDisabled()`

2022-03-09 12:18 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SwitchAssert.java
>  public class SwitchAssert extends UIAssert<SwitchAssert, Switch> {
- В `labelText` в аннотации убрать 's',  использовать передаваемый параметр
- `enabled`, `disabled`: проверить, надо ли их здесь переопределять. Если надо, то добавить аннотацию, если нет - убрать эти методы

2022-03-10 05:51 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +    public void checked() {
Заменила "checked" на "check"

2022-03-10 05:51 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/SwitchTests.java
> +        basicSwitches.get(5).is().checked();
Убрала лишние проверки

2022-03-10 05:51 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
Обновила комментарий

2022-03-10 05:52 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
>      }
Изменила

2022-03-10 05:52 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SwitchAssert.java
>  public class SwitchAssert extends UIAssert<SwitchAssert, Switch> {
Изменила

2022-03-10 05:53 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/SwitchTests.java
>      }
Упростила тест

2022-03-10 05:53 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +    public boolean isChecked() {
Изменила

2022-03-10 07:24 UTC, Kratlis approved these changes

2022-03-10 09:46 UTC, NewerNaigil requested changes

2022-03-10 09:46 UTC, NewerNaigil commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/SwitchTests.java
> +    public void colorSwitchTest() {
В рамках автоматизации проверку цвета делать нет необходимости. Также интерфейс hasColor, и все его методы, в планах на удаление.  Удали этот тест и имплементацию интерфейса из класса Switch.

2022-03-10 10:20 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/SwitchTests.java
> +    public void colorSwitchTest() {
Удалила

2022-03-10 12:37 UTC, NewerNaigil approved these changes

2022-03-10 12:37 UTC, merged