Material bage, icons and tooltip refactoring #3857
jdi-testing/jdi-light pull request #3892
Opened 2022-03-05 14:34 UTC by MaksimGudovich

2022-03-10 09:54 UTC, Kratlis requested changes
Badge comments

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/BadgeContainer.java
> +
Проверь, можно ли использовать аннотацию UI для badge и icon.

Если нет, то можно исплементировать HasBadge. Тогда, может, можно будет убрать метод `badge()`. 
Если будешь добавлять HasBadge, добавь туда аннотацию `JDIAction` и `core()` перед `find`. 
Также можно создать HasIcon

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/BadgePage.java
> +    public static BadgeContainer primaryColorBadgeContainer;
Обязательно прописывать все локаторы? Они же есть в классе по умолчанию. У одного можно оставить для примера

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/BadgePage.java
>      public static Button buttonReduce;
Можно использовать ButtonGroup

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/BadgePage.java
>      public static Checkbox switchShowZero;
Можно это сделать как Switch?

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/BadgePage.java
>      public static Checkbox switchShowBadge;
И здесь. Можно использовать Switch?

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/BadgePage.java
>      public static Checkbox switchShowBadge;
Не лучше badgeDifferentPosition быть BadgeContainer-ами?

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/test/data/BadgeDataProvider.java
> +    }
Костей было предложено, что лучше передавать индекс вместо самого элемента для разделения данных и кода

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/BadgeTests.java
>                  .and().position("TopRightRectangle");
Подобные проверки есть в других тестах. Можно удалить этот тест

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/BadgeTests.java
>          switchShowZero.check();
Здесь не должна проверяться видимость бейджа?

2022-03-10 09:54 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/BadgeTests.java
> +        secondaryColorBadgeContainer.badge().has().text("10+");
Можно это выделить в отдельный тест

2022-03-10 10:06 UTC, Kratlis requested changes
Tooltip comments. 
Добавить show()

2022-03-10 10:06 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/TooltipTests.java
>      }
Не лучше внести эту логику в тесты? Тесты будут легче читаться

2022-03-10 10:06 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/TooltipTests.java
> +        focusOrTouchButtonWithTooltip.tooltip().has().text("Add");
объединить проверки методом `and()`

2022-03-10 10:06 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/TooltipPage.java
> +    public static TooltipButton focusOrTouchButtonWithTooltip;
Можно упростить локаторы на TooltupPage. И лучше организовать элементы в порядке их расположения на странице

2022-03-11 13:51 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/BadgeTests.java
> +        secondaryColorBadgeContainer.badge().has().text("1")
Можно объединить проверки

2022-03-11 14:08 UTC, Kratlis commented
Есть баг с ShowZero #3615

2022-03-11 14:42 UTC, Kratlis approved these changes

2022-03-14 14:20 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/BadgeTests.java
> +                .and().has().text("1")
One test might have a color check. But don't use PRIMARY and SECONDARY enum items

2022-03-14 14:25 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/TooltipTests.java
>   * To see an example of Tooltip web element please visit
Можно убрать этот комментарий, так как в Tooltip это уже указано

2022-03-14 14:25 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/TooltipTests.java
>   * To see an example of Tooltip web element please visit
Можно убрать этот комментарий, так как в Tooltip это уже указано

2022-03-14 14:26 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/test/data/MaterialIconDataProvider.java
> +                {iconsList.get(3), Colors.SECONDARY.rgba(), ""}
Лучше передавать индексы, а не элементы. Для разделения тестовых данных от кода

2022-03-15 11:21 UTC, Kratlis approved these changes

2022-03-15 11:45 UTC, NewerNaigil approved these changes

2022-03-15 11:45 UTC, merged