3854 Material UI: Chip tests refactoring
jdi-testing/jdi-light pull request #3898
Opened 2022-03-10 13:37 UTC by annav00

Moved logic from chipCommonTestLogic methods to test methods.
Removed redundant checks.

2022-03-11 11:15 UTC, Kratlis requested changes
Сейчас в тестах проверяются icon, avatar, link, delete. Можно добавить проверку disabled

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
> +        chip.is().clickable();
Лучше объединять проверки одного элемента методом and()

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
> +        chip.is().clickable();
Тоже объединить проверки

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
>          lastClickArrayInfo.has().text(clickInfoText);
Это можно не проверять. Этот тест проверяет удаление

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/ChipsPage.java
>      public static List<Chip> arrayChips;
Расположи элементы в их порядке на странице, пожалуйста

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +    }
Можно удалить. Это внешний вид

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
>      }
Нужно реализовывать CanBeDisabled и переопределять метод? Может, будет достаточно поведения из ICoreElement

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
>      }
Можно эти элементы сделать полями с аннотацией UI? Метод label() мог бы возвращать поле лейбл

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/ChipAssert.java
>      }
Эти методы необходимо переопределять? Если да - надо добавить аннотацию, если нет - удалить их

2022-03-11 11:15 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/ChipAssert.java
>      public ChipAssert outlined() {
Можно это не проверять

2022-03-13 20:31 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
> +    public void basicFunctionalityChipTest() {
Убрала

2022-03-13 20:31 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
> +        chip.is().clickable();
Исправила

2022-03-13 20:31 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
> +        chip.is().clickable();
Исправила

2022-03-13 20:32 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
>          lastClickArrayInfo.has().text(clickInfoText);
Убрала

2022-03-13 20:32 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/displaydata/ChipsPage.java
>      public static List<Chip> arrayChips;
Исправила

2022-03-13 20:33 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
>      }
CanBeDisabled нужен, переопределение метода убрала

2022-03-13 20:33 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +    }
Удалила

2022-03-13 20:34 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/ChipAssert.java
>      }
Удалила

2022-03-13 20:34 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/ChipAssert.java
>      public ChipAssert outlined() {
Убрала

2022-03-13 21:05 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
>      }
Добавила поля с аннотацией UI. Посмотри, пожалуйста, изменения, правильно ли я тебя поняла

2022-03-14 07:26 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
>      }
Да, поля так и представляла. Только название переменных можно упростить: muiChipLabel -> label. 
Методы их получения, думаю, можно убрать. Кроме `label()`, так как он в интерфейсе

2022-03-14 08:01 UTC, Kratlis requested changes

2022-03-14 08:01 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
> +        chip.is().deletable();
Можно объединить проверки

2022-03-14 08:01 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
>      }
Можно эти методы удалить?

2022-03-14 09:04 UTC, tsvetaevAlex commented
file: jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
line 9: import static io.github.com.pages.displaydata.ChipsPage.*;
NOTE:
need to expand .*; imports.
use only required imports
estimated time to fix:10-15 mins

2022-03-14 15:26 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/ChipTests.java
> +        chip.is().deletable();
Объединила

2022-03-14 15:28 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
>      }
Удалила методы, оставила прямое обращение к полям

2022-03-15 08:18 UTC, NewerNaigil approved these changes

2022-03-15 08:18 UTC, merged