Task #3851 - Radio buttons refactoring
jdi-testing/jdi-light pull request #3912
Opened 2022-03-16 06:49 UTC by foria1405

- Add check without selected data 
- Check that error is displayed

2022-03-16 07:24 UTC, Kratlis requested changes

2022-03-16 07:24 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
> +        quizRadioButtons.has().enabled("The best!", "The worst.");
Можно объединить проверки одного элемента методом `and()`

2022-03-16 07:24 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
> +        //Check that error is displayed
Комментарии можно убрать

2022-03-16 07:24 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
> +        quizAnswer.has().text(containsString("Sorry, wrong answer!"));
Можно проверить красный цвет?

2022-03-16 08:38 UTC, foria1405 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
> +        quizAnswer.has().text(containsString("Sorry, wrong answer!"));
Да, проверила. Также проверила серый цвет текста, когда нет ошибки и возникает You got it!

2022-03-21 11:09 UTC, Kratlis requested changes

2022-03-21 11:09 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
>          labelPlacementRadioButtons.has().selected("Top");
Можно объединить подобные проверки методом and()?

2022-03-23 13:59 UTC, foria1405 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
>          labelPlacementRadioButtons.has().selected("Top");
Объединила

2022-03-23 13:59 UTC, foria1405 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
>      public void quizTest() {
Разделила на правильный и неправильный ответы

2022-03-24 04:43 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
> +        quizRadioButtons.has().enabled("The best!", "The worst.");
Проверь ещё в других местах. Объединение проверок позволяет не искать один и тот же элемент несколько раз

2022-03-24 07:53 UTC, NewerNaigil requested changes

2022-03-24 07:53 UTC, NewerNaigil commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
> +    public void quizWrongAnswerTest() {
На quiz тесты было требование от Натальи Пожидаевой добавить проверку без выбора ответов. Комментарий был удалён, но требование не реализовано.

2022-03-24 13:41 UTC, foria1405 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
> +    public void quizWrongAnswerTest() {
Был добавлен quizTextTest() - тест без выбора данных. В этом тесте проверяется, что текст кнопок, достпуность кнопок, проверяется текст квиза и цвет текста.

2022-03-24 14:13 UTC, foria1405 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/inputs/RadioButtonsTests.java
> +    public void quizWrongAnswerTest() {
Исправила quizTextTest(). Теперь он проверяет текст и цвет текста квиза до нажатия кнопки Check answer и после.

2022-03-24 14:20 UTC, merged