Task 3904: Refactor Accordion
jdi-testing/jdi-light pull request #3913
Opened 2022-03-16 15:25 UTC by lyubavinaju

Accordion extends UIBaseElement instead of Dropdown, necessary methods implemented, custom ControlledAccordion deleted and its logic moved to Accordion.

2022-03-16 15:44 UTC, Kratlis requested changes

2022-03-16 15:44 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AccordionTests.java
>          disabledAccordion.is().disabled();
Проверки одних и тех же элементов можно объединить методом and()

2022-03-16 15:44 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AccordionTests.java
>      public void accordionExpandTest() {
Если возможно, раздели тесты на минисекции пустыми строками, чтобы легче читалось

2022-03-21 11:14 UTC, Kratlis requested changes

2022-03-21 11:14 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/Accordion.java
> +    }
Можно создать интерфейс типа CanBeExpanded

2022-03-21 11:14 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/surfaces/AccordionAssert.java
> +        jdiAssert(element().isExpanded(), Matchers.is(true));
На true/false не стоит делать - логи непонятные. Лучше использовать тернарный оператор

2022-03-23 03:28 UTC, Kratlis approved these changes

2022-03-23 07:58 UTC, NewerNaigil approved these changes

2022-03-23 07:58 UTC, merged