Task 3902: Drawer refactoring
jdi-testing/jdi-light pull request #3916
Opened 2022-03-17 09:58 UTC by rvasilyev

Drawer, DrawerAssert and Drawer tests refactored.

2022-03-17 10:39 UTC, Kratlis requested changes

2022-03-17 10:39 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Drawer.java
>                  .map(String::toLowerCase)
getPosition может возвращать Position? Пример - labelPosition в Checkbox

2022-03-17 10:39 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/DrawerAssert.java
>      public DrawerAssert numberOfListItems(int numberOfListItems) {
В аннотации лучше использовать аргументы метода

2022-03-17 10:39 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/DrawerAssert.java
>      public DrawerAssert numberOfListItems(int numberOfListItems) {
Нужна эта проверка в Drawer? Можно получать конкретный лист и проверять его размер

2022-03-17 10:39 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/navigation/drawer/ClippedDrawerTests.java
>          clippedDrawer.has().numberOfListItems(7);
Проверки одного элемента лучше объединять методом and(). Будет лучше читаться

2022-03-18 09:16 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/DrawerAssert.java
>      public DrawerAssert numberOfListItems(int numberOfListItems) {
Думаю, что нужна. Это удобно для проверки общего числа ListItems, если листов много.

2022-03-18 12:16 UTC, Kratlis requested changes
Обсуждены: 
- оформление тестов
- добавление проверки раскрытия MiniDrawer

2022-03-18 15:26 UTC, Kratlis approved these changes

2022-03-21 13:38 UTC, NewerNaigil approved these changes

2022-03-21 13:38 UTC, merged