Task3905: Lists refactoring
jdi-testing/jdi-light pull request #3920
Opened 2022-03-18 15:04 UTC by rvasilyev

List and dependent classes refactored.

2022-03-21 09:42 UTC, Kratlis requested changes
Насчёт именования надо поговорить с Костей. Как лучше: "List" в начале или в конце имени класса

2022-03-21 09:42 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/MUIListItemAssert.java
>      @JDIAction("Assert that '{name}' has expected text")
Добавь к аннотациям параметр

2022-03-21 09:42 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/MUIList.java
> +    public MUIListItem getItemByText(String itemText) {
может метод называться item?

2022-03-21 09:42 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/MUIList.java
> +    public void selectItemByText(String itemText) {
Может метод называться select?

2022-03-21 09:42 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/MUIListItem.java
> -public class ListItem extends UIBaseElement<ListItemAssert> implements IsText, HasClick, CanBeDisabled {
Проверь, можно ли использовать какие-нибудь интерфейсы наши? HasIcon?

2022-03-21 10:06 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/MUIList.java
> +    public MUIListItem getItemByText(String itemText) {
Думаю, да.

2022-03-21 10:07 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/MUIList.java
> +    public void selectItemByText(String itemText) {
Я думаю, что он вообще избыточен, т.к. вызывает getItemByText().click(). Думаю, его можно удалить.

2022-03-21 11:03 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/MUIListItemAssert.java
>      @JDIAction("Assert that '{name}' has expected text")
Оставляем для таски по ListItem

2022-03-21 11:04 UTC, Kratlis approved these changes

2022-03-22 07:46 UTC, NewerNaigil approved these changes

2022-03-22 07:46 UTC, merged