Task 3483: Implement materialUI alert element
jdi-testing/jdi-light pull request #3921
Opened 2022-03-21 07:47 UTC by MaksimGudovich

Implement materialUI alert element

2022-03-22 09:30 UTC, annav00 requested changes

2022-03-23 08:39 UTC, annav00 approved these changes

2022-03-24 04:38 UTC, Kratlis requested changes

2022-03-24 04:38 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/feedback/AlertTests.java
> +    }
Здесь можно ещё проверить класс алерта

2022-03-24 04:38 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/feedback/AlertPage.java
> +    @UI(".MuiCollapse-container")
Можно в локаторе указать класс MuiAlert-root?

2022-03-24 04:38 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Alert.java
> +    }
Этот метод надо переопределять? Обнови ещё, пожалуйста, HasIcon: добавь core() и аннотацию JDIAction

2022-03-24 11:09 UTC, Kratlis requested changes
Обсудили небольшие замечания: поправить аннотацию в HasIcon, оформление тестов, локатор. 
Добавить javadoc

2022-03-24 20:38 UTC, Kratlis requested changes
По основной работе комментариев нет. Только по джавадоку. Думаю, стоит добавить джавадок для HasIcon, так как это публичный интерфейс

2022-03-24 20:38 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Alert.java
> +     */
Надо ли здесь указывать see, если в описании return есть ссылка на Text?

2022-03-25 07:49 UTC, Kratlis approved these changes

2022-03-25 08:02 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/AlertWithButton.java
> +public class AlertWithButton extends Alert {
Отсутствует javadoc.

2022-03-25 08:27 UTC, rvasilyev requested changes

2022-03-25 08:27 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/AlertWithButton.java
> +public class AlertWithButton extends Alert {
В этом классе тоже нужно добавить javadoc.

2022-03-25 09:34 UTC, rvasilyev approved these changes

2022-03-25 09:53 UTC, NewerNaigil approved these changes

2022-03-25 09:53 UTC, merged