Task 3836: Refactoring ListsTests Rework
jdi-testing/jdi-light pull request #3924
Opened 2022-03-22 08:21 UTC by annav00

Tests with private methods have been changed to use a data provider.

2022-03-22 13:36 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        });
Можно проверить только один элемент

2022-03-22 13:41 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/ListItemAssert.java
>      }
Можно проверять title и subtitle напрямую в тестах, используя ассерты Text?

2022-03-22 13:45 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +    @JDIAction("Get {name}'s subtitle")
Просмотри аннотации в классах

2022-03-22 13:46 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +    @JDIAction(level = LogLevels.DEBUG)
Лучше убрать level из аннотации и использовать дефолтный уровень

2022-03-23 12:45 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +    public static void setup() {
Исправила

2022-03-23 12:46 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/ListItemAssert.java
>      }
Сделала проверка с помощью TextAssert

2022-03-23 12:46 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +    @JDIAction(level = LogLevels.DEBUG)
Изменила аннотацию

2022-03-23 12:46 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +    @JDIAction("Get {name}'s subtitle")
Изменила аннотации

2022-03-23 12:46 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        });
Исправила

2022-03-23 14:40 UTC, Kratlis requested changes

2022-03-23 14:40 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        subGroupList.is().sublistCollapsed("Users");
Можно проверить, что элементов не видно?

2022-03-23 14:40 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        ListItem item = threeLineList.item(1);
Можно проверить, что класс листа v-list--three-line

2022-03-23 14:40 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        twoLinesAndSubheaderList.show();
Можно проверить, что класс листа v-list--two-line

2022-03-23 14:40 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/data/ListsTestsDataProvider.java
> +    public static Object[][] basicFunctionalityTestsData() {
Проверь чекстайлом. Может потребоваться убрать static

2022-03-23 14:40 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/VuetifyListAssert.java
>      }
Можно эти проверки переместить в ListItem?

2022-03-23 14:40 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +        return new Subheader().setCore(Subheader.class, this.core().finds(".v-subheader").get(index));
Можно убрать this?

2022-03-24 15:25 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +        return new Subheader().setCore(Subheader.class, this.core().finds(".v-subheader").get(index));
Убрала

2022-03-24 15:25 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
>      }
Удалила

2022-03-24 15:25 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/data/ListsTestsDataProvider.java
> +    public static Object[][] basicFunctionalityTestsData() {
Чекстайл ничего не говорит про static здесь

2022-03-24 15:25 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +    }
Добавила проверку текста

2022-03-24 15:25 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +    }
Сделала

2022-03-24 15:25 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        ListItem itemAvatar = simpleAvatarListList.item(1);
Сделала

2022-03-24 15:25 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        twoLinesAndSubheaderList.show();
Добавила проверку

2022-03-24 15:25 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        ListItem item = threeLineList.item(1);
Добавила проверку

2022-03-29 07:03 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +    }
Перенесла в ListItem

2022-03-29 07:03 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/VuetifyListAssert.java
>      }
Перенесла в ListItem

2022-03-29 07:03 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> +        subGroupList.is().sublistCollapsed("Users");
Добавила проверку

2022-03-29 14:09 UTC, Kratlis requested changes
Обсудили, что надо подумать над получением элементов. Постараться убрать ассерт itemNotDisplayed. 
Возможные решения: 
- использовать локальную переменную
- искать все, даже скрытые, элементы листа с помощью отдельного метода (надо попробовать)

2022-04-05 08:27 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/composite/ListsTests.java
> -        threeLineList.is().threeLine();
Изменила

2022-04-05 10:41 UTC, Kratlis approved these changes

2022-04-05 10:41 UTC, Kratlis requested changes
Добавить джавадоки. Когда добавишь, можешь у Ромы запросить ревью

2022-04-07 15:25 UTC, Kratlis requested changes

2022-04-07 15:25 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/ListItemAssert.java
>  public class ListItemAssert extends UIAssert<ListItemAssert, ListItem> {
Может реализовывать ITextAssert? Тогда надо будет подкорректировать `text()`

2022-04-07 15:25 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
>          return new Text().setCore(Text.class, find(".v-list-item__title"));
core().find. И для других методов

2022-04-07 15:25 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +     * Gets the action text of the list item.
Можно описать, что такое action text?

2022-04-07 15:25 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
>          return attr("class").contains("active");
core().attr(...). В методе ниже тоже

2022-04-07 15:25 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
>          return core().finds(".v-list-item");
Для protected метода тоже нужен джавадок

2022-04-07 15:25 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +     * @return items as {@link List<ListItem>}
Можно просто List: {@link List}

2022-04-07 19:15 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/ListItemAssert.java
> +     */
Нормально ли будет оставить этот участок без джавадока?

2022-04-08 08:18 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/ListItemAssert.java
> +     */
Удалила

2022-04-08 08:34 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/ListItemAssert.java
>  public class ListItemAssert extends UIAssert<ListItemAssert, ListItem> {
Реализовала

2022-04-08 08:35 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
>          return new Text().setCore(Text.class, find(".v-list-item__title"));
Исправила

2022-04-08 08:36 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
>          return attr("class").contains("active");
Исправила

2022-04-08 08:36 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +     * @return items as {@link List<ListItem>}
Исправила

2022-04-08 08:52 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
>          return core().finds(".v-list-item");
Добавила

2022-04-08 09:11 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +     * Gets the action text of the list item.
Добавила

2022-04-08 09:19 UTC, Kratlis approved these changes

2022-04-08 10:31 UTC, rvasilyev requested changes

2022-04-08 10:31 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +     * @return text as {@link String}
Title text of the list item или text of the list item? Это одно и то же?

2022-04-08 10:31 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +     * @return action text as {@link Text}
Здесь, как и с title text, meta text или action text? Что он собой представляет?

2022-04-08 10:31 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +    public List<ListItem> items() {
Описание фактически идентично itemsWebList(), кроме возвращаемого значения. Я бы расписал подробнее, возможно, с пояснением, зачем тот или иной метод нужен. В противном случае один из методов кажется лишним.

2022-04-08 13:05 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +     * @return action text as {@link Text}
В документации https://vuetifyjs.com/en/components/lists/#action-stack написано "meta text", при этом локаторе используется "action-text". Это текст возле элемента action.

2022-04-08 13:10 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +    public List<ListItem> items() {
Добавила описание для itemsWebList() и items()

2022-04-08 13:27 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +     * @return action text as {@link Text}
ок

2022-04-08 13:31 UTC, rvasilyev requested changes

2022-04-08 13:31 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +    public List<ListItem> items() {
Ок, только ссылки на классы нужно оформить как ссылки.

2022-04-08 14:19 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +     * @return action text as {@link Text}
а можно сказать, что это additional text? "Gets the additional text next to action list item."

2022-04-11 06:00 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/ListItem.java
> +     * @return action text as {@link Text}
Можно и additional, но мне кажется, что meta больше подходит. Плюс момент с уже существующей документацией.

2022-04-11 06:04 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/composite/VuetifyList.java
> +    public List<ListItem> items() {
Добавила ссылки

2022-04-11 08:21 UTC, rvasilyev approved these changes

2022-07-21 05:40 UTC, merged