Task 3919: Refactor data providers and asserts
jdi-testing/jdi-light pull request #3926
Opened 2022-03-22 08:39 UTC by rvasilyev

Asserts refactored, new data providers created.

2022-03-22 10:42 UTC, Kratlis requested changes
Проверить аннотации

2022-03-22 18:07 UTC, Kratlis requested changes

2022-03-22 18:07 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/surfaces/CardAssert.java
> +    @JDIAction("Assert that '{name}' has title {0}")
Лучше: Assert that '{name}' title {0}. Так же с остальными матчерами

2022-03-23 12:57 UTC, Kratlis requested changes

2022-03-23 12:57 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/DateTimePickerAssert.java
> +    public DateTimePickerAssert text(Matcher<String> condition) {
Лучше без has: Assert that {name} text {0}

2022-03-23 12:57 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SliderRangeAssert.java
> +  @JDIAction("Assert that '{name} 'orientation is '{0}'")
Переместить кавычку

2022-03-23 12:57 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/TransferListAssert.java
>      public TransferListAssert itemsMovedRight(String... items) {
Здесь тоже можно использовать параметр: Assert that '{name}' items {0} were moved right. Но не уверена, как это будет выглядеть

2022-03-23 12:57 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/utils/ModalAssert.java
> +    @JDIAction("Assert that {name} has text {0}")
Здесь тоже можно убрать has

2022-03-24 08:05 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/TransferListAssert.java
>      public TransferListAssert itemsMovedRight(String... items) {
Скорее всего, items будет выведен как строковое представление массива.

2022-03-25 09:36 UTC, Kratlis approved these changes

2022-03-25 12:32 UTC, NewerNaigil approved these changes

2022-03-25 12:32 UTC, merged