Task 3915: fix issues founded by check style
jdi-testing/jdi-light pull request #3934
Opened 2022-03-23 12:17 UTC by b14ckster

Fixing problems concerned only "jdi-light-material-ui"

2022-03-24 08:02 UTC, Kratlis commented
Исправь конфликт. И я не уверена, можем ли мы менять MaterialActions. Уточни у Кости

2022-03-24 20:53 UTC, Kratlis requested changes

2022-03-24 20:53 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/actions/MaterialActions.java
> +            logger.trace("<>@AA: %s >>> %s", classMethod, result == null ? "NO RESULT" : result);
Можем ли мы изменять этот класс?

2022-03-25 08:56 UTC, NewerNaigil approved these changes

2022-03-25 08:56 UTC, NewerNaigil commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/actions/MaterialActions.java
> +            logger.trace("<>@AA: %s >>> %s", classMethod, result == null ? "NO RESULT" : result);
Функционал этого класса не надо менять. Однако данные изменения CheckStyle и они минорные. Считаю их допустимыми.

2022-03-25 08:57 UTC, merged