Task 3810: vuetify avatars refactoring
jdi-testing/jdi-light pull request #3936
Opened 2022-03-23 15:08 UTC by b14ckster

Deleted methods and created Data Provider for method "avatarsWithSizeTests".

2022-03-24 08:08 UTC, Kratlis commented
Исправь замечание по кодаси и проверь файлы чекстайлом. Может потребоваться убрать static из дата провайдера. 
Можно в классе ассерта использовать какой-нибудь интерфейс для проверки текст? Например, ITextAssert

2022-03-24 20:50 UTC, Kratlis requested changes
Надо добавить джавадоки в ассерты

2022-03-24 20:50 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/common/AvatarsTests.java
>          avatarsWithSize.forEach(avatar -> avatar.is().displayed());
Если в дата провайдере передаётся индекс элемента, то можно проверять displayed только у него

2022-03-24 20:50 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/common/AvatarsTests.java
>      @Test
В profileCardTests можно объединить проверки

2022-03-24 20:50 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/AvatarAssert.java
По аннотации у `size`. Надо ли использовать кавычки около {0}? Можно заменить тип параметра на int и не указывать кавычки

2022-03-24 20:50 UTC, Kratlis commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/asserts/ProfileCardAssert.java
>      public ProfileCardAssert userName(String text) {
В аннотации надо использовать передаваемый параметр: "Assert that '{name}' has username '{0}'". И поправь у второго метода

2022-03-25 15:13 UTC, Kratlis requested changes

2022-03-25 15:13 UTC, Kratlis commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/common/AvatarsTests.java
> +        avatarsWithSize.get(avatarNumber).has().size(avatarSize);
Можно объединить

2022-03-25 15:13 UTC, Kratlis commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/asserts/ProfileCardAssert.java
>          return this;
Убрать пустую строку перед закрывающейся скобочкой класса

2022-03-30 14:18 UTC, b14ckster commented
Added javadocs for asserts: AvatarAssert and ProfileCardAssert

2022-03-31 07:22 UTC, rvasilyev requested changes

2022-03-31 07:22 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/AvatarAssert.java
> +     * Checks text in {@link Avatar}.
Лучше как-то вроде Checks that text in {@link Avatar} meets given condition.

2022-03-31 07:22 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/AvatarAssert.java
> +     * @param condition Matcher for checking text.
Лучше @param condition expected condition. Ссылка на тип параметра и так будет доступна в сигнатуре.

2022-03-31 07:22 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/AvatarAssert.java
> +     * Checks {@link Avatar} size.
Для единообразия: Checks that {@link Avatar} has expected size.

2022-03-31 07:22 UTC, rvasilyev commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/AvatarAssert.java
> +     * @param size size of avatar in pixels.
@param size expected size of avatar in pixels.

2022-04-01 14:06 UTC, Kratlis requested changes
Добавь джавадоки для ProfileCard, HasIcon, HasImage. И проверь элементы в соответствии с Инструктажом

2022-04-08 07:12 UTC, Kratlis requested changes

2022-04-08 07:12 UTC, Kratlis commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/ProfileCard.java
> + *
Ссылку надо оформить по-другому, как обычно в элементах

2022-04-08 07:12 UTC, Kratlis commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/ProfileCard.java
>      @JDIAction("Get '{name}'s avatar image")
Убери 's' из аннотаций

2022-04-08 07:12 UTC, Kratlis commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/ProfileCard.java
>          return new Image().setCore(Image.class, finds(IMAGES_LOCATOR).get(2));
Добавь `core()` перед `find/finds`

2022-04-08 07:12 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/AvatarAssert.java
>      public AvatarAssert size(Integer size) {
Может параметр метода быть примитивом? int

2022-04-08 07:12 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/Avatar.java
Надо добавить джавадок для аватара

2022-04-08 07:12 UTC, Kratlis commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/interfaces/HasImage.java
>          return new Image().setCore(Image.class, find("img"));
Добавь core() в интерфейсы

2022-04-08 10:44 UTC, rvasilyev requested changes

2022-04-08 10:44 UTC, rvasilyev commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/ProfileCard.java
>   * To see an example of Profile card web element please visit https://vuetifyjs.com/en/components/avatars/#profile-card
Посмотри, как оформлять @see.

2022-04-08 10:44 UTC, rvasilyev commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/ProfileCard.java
> +     * Locators for avatar and background images, username and job function.
Этот джавадок здесь не нужен, или надо писать для каждого поля. Для приватных полей джавадоки не обязательны.

2022-04-08 10:44 UTC, rvasilyev commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/ProfileCard.java
> + *
Для класса нужно писать, что он собой представляет и потом уже частности, например: Represents profile card Vuetify component on GUI. Profile card contains avatar image, background image, username and job function.

2022-04-08 11:29 UTC, tsvetaevAlex commented
6 issues found due to:
javadoc tag '@return' should be preceded with an empty line.
affected 
file:jdi-light-vuetify-tests/src/main/java/io/github/com/custom/ProfileCard.java
issues details:
https://app.codacy.com/gh/jdi-testing/jdi-light/pullRequest?prid=9112988

2022-04-12 14:22 UTC, Kratlis approved these changes

2022-04-14 09:57 UTC, rvasilyev approved these changes

2022-04-29 16:32 UTC, rvasilyev approved these changes

2022-07-16 01:34 UTC, merged