Task 3856: Refactor Table Test
jdi-testing/jdi-light pull request #3942
Opened 2022-03-24 13:19 UTC by IvKardapolov

Refactor basic table, data table, collapsing table tests. Rework table into collapsing table like a inner table

2022-03-28 15:35 UTC, Kratlis requested changes

2022-03-28 15:35 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/asserts/TableAssert.java
> +public class TableAssert extends BaseTableAssert<Table, TableAssert> {
Попробовать обойтись дефолтными ассертами

2022-03-28 15:35 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/CollapsingTable.java
> +    @JDIAction("Get inner table from row '{0}'")
Надо добавить в аннотации параметр '{name}'

2022-03-28 15:35 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/InnerTable.java
> +    public InnerTable() {
Лучше вставить пустую строку перед методом. И надо добавить аннотацию с описанием

2022-03-28 15:35 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/MuiCacheAll.java
> +    public MuiCacheAll() {
Лучше вставить пустую строку перед методом. Второй конструктор лучше развернуть на три строчки

2022-03-28 15:35 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/TableTests.java
> +        collapsibleTable.expandRow(5);
Проверь, чтобы в начале тестовых методов был show()

2022-03-28 15:35 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/displaydata/TableTests.java
> +
Здесь можно убрать пару пустых строк. Сделать менее дроблённым. Можно даже объединить sendKeys и ассерты после него в один блок

2022-03-29 06:30 UTC, IvKardapolov commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/InnerTable.java
> +    public InnerTable() {
jdi аннотации непременимы для конструкторов. Какую аннотацию вставить?

2022-03-29 12:16 UTC, Kratlis requested changes
Осталось добавить джавадоки

2022-03-30 09:46 UTC, Kratlis requested changes
Для Override методов можно не писать джавадоки, если поведение такое же. 
Посмотри, можно ли добавить использование тегов `@see` и `@link`. 
Проверь ещё раз оформление на соответствие Инструктажу и посмотри этот [ПР по джавадоку](https://github.com/jdi-testing/jdi-light/pull/3953)

2022-03-31 08:28 UTC, rvasilyev requested changes

2022-03-31 08:28 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/TableWithFilters.java
> +     * Used in waiter.
Строка с этой информацией лишняя.

2022-03-31 08:28 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/TableWithFilters.java
> +    @JDIAction("Click '{name}' button '{0}' by Actions")
Этот javadoc нужно полностью переделать в соответствии с руководством.

2022-03-31 08:28 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/utils/WesterosUser.java
> +public class WesterosUser extends Section {
Для этого класса и его компонентов также нужен javadoc.

2022-03-31 08:28 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/utils/UserInfo.java
> +public class UserInfo extends DataClass<UserInfo> {
Для этого класса и его компонентов также нужен javadoc.

2022-04-01 09:39 UTC, rvasilyev requested changes
Не все замечания исправлены. Есть ошибки Codacy.

2022-04-01 13:12 UTC, IvKardapolov commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/MuiCacheAll.java
> + * Inherited from CacheAll for use protected method isGotAll().
> Эта строка лишняя.
На этой строке настаивала Катя. Требуется консенсус по этому вопросу

2022-04-04 11:55 UTC, rvasilyev requested changes

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/CollapsingTable.java
> +     * @return table in expanded row {@link InnerTable} instance from inner tables array.
table in expanded row as {@link InnerTable} - будет достаточно, остальное - подробности реализации, которые не надо указывать.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/CollapsingTable.java
> +     * Expands row and fills innerTables array with created Inner Table.
Expands row или Expands row with given index будет достаточно.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/CollapsingTable.java
> +     * Collapses row.
Ну или Collapses row with given index, лучше единообразно с предыдущим методом.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/InnerTable.java
> +     * Constructor
Конструктор описывается более развернуто, например Creates new {@link InnerTable} instance.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/MuiCacheAll.java
> + * @param <T> type which class contains in Supplier getRule {@link com.jdiai.tools.CacheValue}.
Судя по всему, здесь неверно описана суть параметра. Это тип кэшируемого параметра, насколько я понял по коду и иерархии наследования. Также можно дать ссылку на CacheValue в @see.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/MuiCacheAll.java
> +     * Default constructor.
Как и в предыдущем случае - более развернутое описание.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/MuiCacheAll.java
> +     * Constructor.
Как и в предыдущем случае - более развернутое описание.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/MuiCacheAll.java
> +     * @param getRule type will be set in Supplier getRule {@link com.jdiai.tools.CacheValue}.
Судя по всему - это JFunc для описания механизма получения значения по умолчанию.  Вообще, дабы избежать пустых реализаций и тривиальных/непонятных javadoc я бы подумал о правомочности здесь параметризованного конструктора. Коль скоро есть сеттер, зачем конструктор, который и так его вызывает и заставляет явно определять пустой конструктор без параметров? Тем более ,что из доков сеттера будет более понятно назначение парметра и можно более подробно описать нюансы работы, не дублируя их в других местах. Как вариант можно создать один конструктор с varargs и дать ссылку на сеттер в родителе.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/TableWithFilters.java
> + * @param <L> @see Data transfer object with UIElement fields from row {@link io.github.com.pages.utils.WesterosUser}
Тэг @see не надо размещать в @param. При описании я сослался бы на родительский класс или вообще написал бы, что описание аналогично таковому в родительском классе и смотреть нужно в нем.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/TableWithFilters.java
> + * @param <D> @see Data transfer object with String fields from row {@link io.github.com.pages.utils.UserInfo}
То же, что и в предыдущем случае.

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/custom/elements/table/TableWithFilters.java
> +     * Hover and clicks on the button.
Hovers (опечатка).

2022-04-04 11:55 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/utils/WesterosUser.java
> +public class WesterosUser extends Section {
Здесь описание одинаково с предыдущиим DTO. В чем между ними разница, в каких случаях использовать один, а в каких другой? Это все нужно описать для обоих классов.

2022-04-05 09:25 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/utils/WesterosUser.java
> +public class WesterosUser extends Section {
Значит это и другие подобные пояснения надо указать в Javadoc.

2022-04-07 15:30 UTC, rvasilyev requested changes

2022-04-08 10:16 UTC, rvasilyev approved these changes

2022-04-27 07:41 UTC, Kratlis approved these changes

2022-05-20 10:41 UTC, dobriyanchik approved these changes

2022-05-20 10:41 UTC, merged