Added JavaDoc
jdi-testing/jdi-light pull request #3960
Opened 2022-03-28 14:13 UTC by kalimullina

Wrote JavaDoc according to the tutorial in "Инструктаж для новичков".

Elements for Javadoc: TransferList

2022-03-28 14:19 UTC, Kratlis requested changes
Надо создать джавадоки для связанных с этим элементом классов

2022-03-28 14:19 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/EnhancedTransferList.java
>      public void moveAllElementsLeft() {
Поправь аннотации в классах

2022-03-29 17:14 UTC, Kratlis requested changes
Надо добавить джавадок для аннотации JDITransferList

2022-03-29 17:14 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/TransferListAssert.java
>  public class TransferListAssert extends UIAssert<TransferListAssert, TransferList> {
Надо сделать джавадок для самого класса тоже

2022-03-29 17:14 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/TransferListAssert.java
> +     * @return {@link TransferListAssert}
Посмотри в [ПР](https://github.com/jdi-testing/jdi-light/pull/3953) оформление ассертов и комментарии Ромы

2022-03-29 17:14 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/EnhancedTransferList.java
> +    @JDIAction("Move all {name} elements left")
В джавадоке заменить Selectors на Selects. Не уверена, насколько нужно указывать, что это только для Enchanced трансфер лист. Мы же уже в этом классе.  
В аннотации у параметра {name} должны быть кавычки: '{name}'

2022-03-29 17:16 UTC, Kratlis commented
Укажи в названии ПР-а, для какого элемента ты пишешь джавадоки

2022-04-01 09:41 UTC, Kratlis requested changes
Запроси ревью, когда исправишь все замечания. Мне так будет удобнее

2022-04-11 15:05 UTC, Kratlis requested changes

2022-04-11 15:05 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +    @JDIAction("Check that '{name}' move right button is enabled")
Можно в аннотации использовать "'Move right' button"?

2022-04-14 10:43 UTC, rvasilyev requested changes

2022-04-14 10:43 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/annotations/JTransferList.java
> + * @see EnhancedTransferList
Раз уже есть ссылки на эти классы, @see лучше убрать.

2022-04-14 10:43 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/annotations/JTransferList.java
> + * Annotation for setting locators for buttons and left/right items list in {@link TransferList} and {@link EnhancedTransferList}.
Я бы не перечислял конкретные типы элементов, они могут меняться. Можно написать просто Annotation for setting locators for {@link TransferList} and {@link EnhancedTransferList}.

2022-04-14 15:12 UTC, rvasilyev requested changes

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     *
Checks checkbox of the item with given text (full equality is used by searching). If it's already checked, does nothing.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @param itemText full text content of item to be checked
@param itemText expected item text

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @param itemText full text content of item to be unchecked
@param itemText expected item text

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @return {@code true} if this button is enabled, otherwise {@code false}
This нужно заменить на название кнопки.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @return {@code true} if this button is disabled, otherwise {@code false}
This нужно заменить на название кнопки.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @return {@code true} if this button is enabled, otherwise {@code false}
This нужно заменить на название кнопки.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @return {@code true} if this button is disabled, otherwise {@code false}
This нужно заменить на название кнопки.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * Checks if specific item is checked or not.
Checks that item with given text is checked or not.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @param itemText full text content of item to be checked
@param itemText expected item text

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @param itemText full text content of item to be unchecked
@param itemText expected item text

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * Checks if specific item is unchecked or not.
Checks that item with given text is unchecked or not.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @return {@code true} if this item is checked, otherwise {@code false}
This нужно заменть на item with given text.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @return {@code true} if this item is unchecked, otherwise {@code false}
This нужно заменть на item with given text.

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @param itemText full text content of item
@param itemText expected item text

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * Gets the checkbox of specific item using the item text (full equality is used by searching).
Gets the checkbox of item with given text (full equality is used by searching).

2022-04-14 15:12 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/transferlist/TransferList.java
> +     * @return element with this text as {@link UIElement}
Судя по всему, здесь неверное описание. @return checkbox of item with given text as {@link UIElement}. Я бы возвращал элемент как Checkbox для возможных проверок в тестах.

2022-04-15 10:29 UTC, rvasilyev approved these changes

2022-04-18 09:48 UTC, NewerNaigil approved these changes

2022-04-18 09:48 UTC, merged