Task 3955: Write Javadoc for TextField
jdi-testing/jdi-light pull request #3962
Opened 2022-03-29 16:10 UTC by Kratlis

### Javadoc is written for:
- TextField
- Interfaces:
  - HasAdornment
    Connected classes:
    - Adornment
    - AdornmentAssert
  - CanBeFocused
  - HasHelperText
  - HasValidationError
  - HasPlaceholder
- TextFieldAssert
- MultilineTextField
- SelectTextField
- Enums (using in tests)
  - Currency
  - Position

### Changes in TextField:
- deleted `hasPlaceholder()`

### Changes in Adornment:
- deleted overriding of method `click()` 
- deleted private method `getButton()`
- deleted overriding of method `has()`

### Other changes:
- added usages of method `core()`
- HasPlaceholder: deleted `hasPlaceholder()`
- HasHelperText: deleted `getHelperText()`
- HasValidationError: renamed method to `isValidationErrorPresent()`

2022-03-30 15:42 UTC, rvasilyev requested changes

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/enums/Currency.java
> +  public String toString() {
Тут как раз тот случай, когда у переопределенного метода лучше написать javadoc, т.к. возвращаемое значение отличается от дефолтного.

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/TextFieldAssert.java
> +     * @param text expected helper text
Наверное, expected placeholder text?

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Adornment.java
> + * For instance, you can use an icon button to hide or reveal the password.
Наверное, for example?

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Adornment.java
> + * Represents an adornment.
Раз уж мы за единообразие, то тогда  "Represents an adornment MUI component on GUI."

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> +     * For macOS the keys that are used for it are 'COMMAND + A + BACK_SPACE'.
Думаю, подробности реализации, какие клавиши где используются, здесь избыточны.

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/TextField.java
> + * Represents text field MUI component on GUI.
Поскольку в документации этого отдельно не выделяется, я бы пояснил, что текстовое пле здесь рассматривается как сложный компонет, ключающие собственно поле ввода, адорнменты, плейсхолдеры и т.п. Это сделало бы более понетным наличие некоторых методов и их поведение в классе.

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/enums/Position.java
> +     */
Я бы добавил сюда @throws.

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/enums/Position.java
> +    public String toString() {
Я бы здесь тоже уточнил, что возвращает эта переопределенная версия, т.к. по дефоту возвращается name(), а тут буддет строка с содержимым в Camel Case.

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasHelperText.java
> +     * Gets the helper text of the element as an element.
Думаю, можно не писать "as an element", это будет в @return

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasHelperText.java
> +     * Gets the helper text of the element as a string.
Здесь тоже можно не уточнять тип возвращаемого значения, это будет в @return

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasPlaceholder.java
> + * The short hint is displayed in the field before the user enters a value.
Грамотней будет написать within the field (т.е. внутри поля).

2022-03-30 15:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/inputs/HasValidationError.java
>      default boolean hasValidationError() {
Здесь также вопрос о правомочности метода в свете названия интерфейса. Может добавить вместо этого метод получения текста ошибки и/или проверки наличия этого текста? Если это невозможно, то тогда этот интерфейс можно оставить маркерным.

2022-03-31 14:34 UTC, rvasilyev approved these changes

2022-04-01 08:39 UTC, NewerNaigil approved these changes

2022-04-01 08:40 UTC, merged