Task 3955: Write Javadoc for Link, Progress
jdi-testing/jdi-light pull request #3967
Opened 2022-03-31 22:00 UTC by Kratlis

## Javadoc is written for:
- Link
  - LinkAssert
  - HasColor
  - IColorAssert
- Progress
  - ProgressAssert
  - LinearProgress
  - LinearProgressAssert
  - CircularProgress
  - JProgress

2022-04-01 10:42 UTC, rvasilyev requested changes

2022-04-01 10:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/feedback/LinearProgressAssert.java
> +     * @return this {@link LinearProgressAssert} instance
Не хватает описания параметра.

2022-04-01 10:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/feedback/LinearProgressAssert.java
> +     * @return this {@link LinearProgressAssert} instance
Не хватает описания параметра.

2022-04-01 10:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/progress/Progress.java
> +     * Locator for progress root.
Возможно, стоит подробнее пояснить, что таоке root?

2022-04-01 10:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/progress/Progress.java
> +     * Locator for label.
То же, возможно, стоит уточнить, что именно за лейбл, если он, конечно, не единственный и не оговорен в документации MUI.

2022-04-01 10:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/progress/Progress.java
> +     * Gets the progress label by searching for the specified locator starting at the root of the page.
Gets the progress label будет достаточно.

2022-04-01 10:42 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/progress/Progress.java
> +     * Checks if the progress is determinate or not (i.e. has value attribute or not).
Наверное, indeterminate?

2022-04-01 16:09 UTC, rvasilyev approved these changes

2022-04-04 10:46 UTC, NewerNaigil approved these changes

2022-04-04 10:47 UTC, merged