Added javadoc to Dialog, Badge, Icon, Tooltip classes.
jdi-testing/jdi-light pull request #3969
Opened 2022-04-01 09:56 UTC by MaksimGudovich

Added javadoc to Dialog, Badge, Icon, Tooltip classes.
There is no MaterialIcon class in material module.

2022-04-01 10:42 UTC, Kratlis requested changes
- Надо добавить джавадок для классов, связанных с этими элементами
- Проверь аннотации: оформаление JDIAction и использование Override
- Попробуй упростить локаторы ([JDI Документация](https://jdi-docs.github.io/jdi-light/#jdi-locators-as-simple-as-css-as-powerful-as-xpath))

2022-04-06 10:05 UTC, Kratlis requested changes

2022-04-06 10:05 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
> +     */
Можно уточнить про лист: Gets the list with items within the dialog.

2022-04-06 10:05 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
> +     * @return buttons of this dialog as {@link ButtonGroup}
Можно рассказать, что такое action кнопки или привести примеры. Также можно использовать 'within'. И в следующих случаях тоже

2022-04-06 10:05 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
>      public Boolean hasScrollableContent() {
Проверь оформление джавадока для boolean метода. И этот метод может возвращать примитив?

2022-04-06 12:26 UTC, rvasilyev requested changes

2022-04-06 12:26 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasBadge.java
> + * Interface for getting a {@link Badge} from an element
Я бы не писал getting, т.к. это только сейчас там один геттер, но в теории может быть что-то еще, например каки-ето булевские проверки. Можно как-то так: Interface for element containing a {@link Badge}.

2022-04-06 12:26 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasIcon.java
> + * Interface for getting a {@link Icon} from an element
Аналогично HasBadge.

2022-04-06 12:26 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasTooltip.java
> + * Interface for getting a {@link Tooltip} from an element
Аналогично HasBadge.

2022-04-07 13:47 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Icon.java
> +     */
В Dialog для hasScrollableBody лучше: "Checks if dialog has scrollable body or not."

2022-04-07 13:48 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Icon.java
> +     */
В Tooltip для isInteractive лучше: "Checks if tooltip is interactive or not."

2022-04-07 14:51 UTC, Kratlis requested changes

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Badge.java
> +     */
не очень понятно, что значит no items. Можно описать по-другому? Здесь же классы проверяются

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Icon.java
>      }
А здесь можно оставить один из методов disabled/enabled?

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Tooltip.java
> +    @JDIAction("Shows that '{name}' is visible")
Check that...?

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Tooltip.java
> +     * is expired, otherwise {@code false}
> if this tooltip doesn't close when the user hovers over the tooltip before the leaveDelay
     * is expired,

Это объяснение, что такое interactive? Можно включить в summary джавадока, например: "Checks if tooltip is interactive or not. Interactive tooltip doesn't close..."

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
> +     * Gets the buttons within the dialog that close the dialog box with or without a confirmation
Добавить точку. "with or without a confirmation" нужно здесь? Какой смысл?

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
> +     *
Checks if dialog...?

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
> +     * @param closeButtonName the name of the button to close the dialog
Добавить throws

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
> +     * @throws RuntimeException if no items found
Описать подробнее, каких items нет. Можно сказать, что нет кнопки с таким текстом

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasBadge.java
> + * Represents an element that has an {@link Badge}
...has a {@link Badge}. Добавить точку

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasBadge.java
> +     * Gets the badge of element.
Лучше badge of **the** element. Можно добавить `@JDIAction`. И `core()` перед `find`

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasTooltip.java
> + * Represents an element that has an {@link Tooltip}
Represents an element that has a {@link Tooltip}. Точку надо добавить

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasTooltip.java
> +     * Gets the tooltip of element.
of the element

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/BadgeAssert.java
>      }
Можно попробовать сравнивать объекты перечисления. [DrawerAssert](https://github.com/jdi-testing/jdi-light/pull/3983/files#diff-2462f2ac2811f6f3b20855f38d884adcdef4e1831548c147b20fec1433ecc3df)

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/IconAssert.java
>      public IconAssert color(Matcher<String> condition) {
Надо добавить Override и убрать джавадок

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Badge.java
>      }
Можно оставить один метод isVisible/isNotVisible?

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Badge.java
> +        String position = Arrays.stream(attr("class")
Надо добавить core().attr(...)

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Icon.java
>          return String.join("", classes()).contains("color") || attr("style").contains("color");
core().classes(), core().attr(...)

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Icon.java
>          return attr("class").contains("colorDisabled");
core().attr(...)

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
>          return new Text().setCore(Text.class, find(".MuiDialogTitle-root"));
core().find. И в остальных методах

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
>      @JDIAction("Get '{name}' input field")
"Get '{name}' text field"

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
>      public Boolean hasScrollableContent() {
Могут boolean методы этого класса возвращать примитив boolean? Не Boolean

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
>      @JDIAction("Scroll '{name}' to target height")
Используй в аннотации параметр, например: "Scroll '{name}' to height '{0}'". 
Для `scrollDialogBodyTo` тоже

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Dialog.java
> +     * Closes this dialog with 'ok' button if it exists.
Сделай так же, как для `close()`: otherwise...

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasBadge.java
>          return new Badge().setCore(Badge.class, find(".MuiBadge-badge"));
core().find

2022-04-07 14:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasIcon.java
> + * Represents an element that has an {@link Icon}
Добавь точку

2022-04-07 15:27 UTC, rvasilyev requested changes

2022-04-07 15:27 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Tooltip.java
> +     * is expired, otherwise {@code false}
Описание относительно  не поправлено.

2022-04-08 09:40 UTC, MaksimGudovich commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Icon.java
>      }
Так как проверка произволится по определенному классу в элементе, то думаю, что стоит оставить оба

2022-04-08 12:14 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/displaydata/HasBadge.java
> +     * Gets the badge of element.
Убрать точки у return

2022-04-08 12:39 UTC, Kratlis approved these changes

2022-04-08 13:22 UTC, rvasilyev approved these changes

2022-04-12 09:24 UTC, NewerNaigil approved these changes

2022-04-12 09:24 UTC, merged