Task 3950: Write Javadoc for Switch, Chip
jdi-testing/jdi-light pull request #3974
Opened 2022-04-04 15:36 UTC by annav00

2022-04-05 10:20 UTC, Kratlis requested changes

2022-04-05 10:20 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     * If the element is not a link, then an exception is thrown.
Про исключение можно написать в джавадоке `@throws`

2022-04-05 10:20 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/ChipAssert.java
> +     *
Может, стоит использовать 'a'? Checks that chip is a link. Тогда надо в аннотации и в методе тоже поменять

2022-04-05 10:20 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +     */
Можно, наверно, сказать проще: Checks tha switch. Или, может, использовать 'state' вместо 'position': sets the switch to the on state.

2022-04-05 10:20 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
>      @Override
Для override методов можно не писать джавадок, если поведение похоже на родительское

2022-04-05 10:59 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SwitchAssert.java
>  public class SwitchAssert extends UIAssert<SwitchAssert, Switch> {
Добавила

2022-04-05 10:59 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SwitchAssert.java
> +     * @return this {@link SwitchAssert} instance
Лучше label text, исправила

2022-04-05 11:01 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     */
Исправила

2022-04-05 11:04 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/ChipAssert.java
> +     *
Согласна, так лучше. Исправила

2022-04-05 11:07 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +     */
Как тебе вариант "Turns on the switch"?

2022-04-05 11:08 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
>   * https://mui.com/components/chips/
Удалила

2022-04-05 11:09 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     */
Ты имеешь ввиду так написать "Icon that represents the ornaments that disappear when clicked."?

2022-04-05 11:28 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +     */
В документации в коде видела только про checked:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/48138888/161744324-a5b1c72a-9c80-456f-b6f8-07f91be33bf8.png">

2022-04-05 11:33 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     */
Если эта иконка удаляет свитч, то можно сказать так: "Icon that represents an ornament that deletes the chip when clicked."

2022-04-05 11:34 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
>      @Override
Исправила

2022-04-05 11:38 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     */
Звучит хорошо, использую этот текст.

2022-04-05 11:55 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     * If the element is not a link, then an exception is thrown.
Исправила

2022-04-07 12:13 UTC, Kratlis requested changes

2022-04-07 12:13 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SwitchAssert.java
> +        jdiAssert(element().label().isDisplayed() ? "has a label" : "has no a label",
Либо 'has no label', либо 'doesn't have a label'

2022-04-07 12:18 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/SwitchAssert.java
> +        jdiAssert(element().label().isDisplayed() ? "has a label" : "has no a label",
Изменила на  'has no label'

2022-04-07 12:19 UTC, Kratlis approved these changes

2022-04-07 14:37 UTC, rvasilyev requested changes

2022-04-07 14:37 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     * @throws RuntimeException chip does not have delete icon
Аналогично, 'Delete' icon.

2022-04-07 14:37 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     * Deletes the chip using the deleteIcon.
Deletes the chip using the 'Delete' icon. Здесь мы ссылаемся не на переменную, а на элемент UI.

2022-04-07 14:37 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> + * Represent switch MUI component on GUI. Switches toggle the state of a single setting on or off.
Здесь я бы уточнил  Switches toggle the state of a single setting on or off ('checked' and 'unchecked' states respectively).

2022-04-07 14:37 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +     * Checks this switch
Checks this switch. If it's already checked, does nothing. В данном случае это существенно, потому что в теории можно ожидать и ошибки из-за невалидного состояния.

2022-04-07 14:37 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +     * Unchecks this switch
Unchecks this switch. If it's already unchecked, does nothing.

2022-04-07 14:45 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +     * Unchecks this switch
Исправила

2022-04-07 14:46 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> +     * Checks this switch
Исправила

2022-04-07 14:46 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Switch.java
> + * Represent switch MUI component on GUI. Switches toggle the state of a single setting on or off.
Исправила

2022-04-07 14:46 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     * Deletes the chip using the deleteIcon.
Исправила

2022-04-07 14:46 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/displaydata/Chip.java
> +     * @throws RuntimeException chip does not have delete icon
Исправила

2022-04-08 07:01 UTC, NewerNaigil approved these changes

2022-04-08 07:02 UTC, merged