Task3963: Work with ButtonGroup as with list
jdi-testing/jdi-light pull request #3980
Opened 2022-04-06 04:43 UTC by lyubavinaju

2022-04-14 10:32 UTC, rvasilyev requested changes

2022-04-14 10:32 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/ButtonGroupAssert.java
> +    @JDIAction("Assert that '{name}' has '{0}' buttons")
Может тут кавычки не нужны?

2022-04-14 10:32 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/ButtonGroup.java
> +    @JDIAction("Get button with index '{0}'")
Здесь тоже, раз цифра?

2022-04-18 09:07 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/inputs/ButtonGroupAssert.java
> +    @JDIAction("Assert that '{name}' has '{0}' buttons")
Решили оставить

2022-04-18 09:07 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/ButtonGroup.java
> +    @JDIAction("Get button with index '{0}'")
Решили оставить

2022-04-19 07:42 UTC, rvasilyev approved these changes

2022-04-21 07:31 UTC, NewerNaigil approved these changes

2022-04-21 07:31 UTC, merged