Task 3946: Write javadoc for drawer, list, box
jdi-testing/jdi-light pull request #3983
Opened 2022-04-06 10:36 UTC by rvasilyev

Javadoc for MUIListItem, MUIListItemAssert, DrawerAssert added. Javadoc for MUIList extended. Ther is no need for javadoc for Box because of its absence. Constants in MUIListItem made private, 2 methods renamed for simplicity.

2022-04-06 14:06 UTC, Kratlis requested changes
Можешь добавить джавадок для CanBeDisabled, MUIListItemWithDialog, ButtonWithDrawer? И проверь файлы, чтобы была пустая строка в начале класса (e.g. BoxPage)

2022-04-06 14:45 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/MUIListItemAssert.java
> +     */
Я бы оставил, как есть, иначе непонятн, что это primary text.

2022-04-06 15:51 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/MUIListItemAssert.java
> +     */
Можно в DrawerAssert у numberOfListItems написать "Checks that list has given number list items."?

2022-04-07 07:21 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/displaydata/MUIListItemAssert.java
> +     */
Это будет неточным, т.к. там айтемы со всех листов, а не только с какого-то одного.

2022-04-07 12:01 UTC, Kratlis requested changes

2022-04-07 12:01 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/base/CanBeDisabled.java
>      }
Зачем этот метод? Спросила Костю

2022-04-07 12:01 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/interfaces/base/CanBeDisabled.java
>      default boolean isDisabled() {
Надо добавить `@JDIAction`

2022-04-07 13:56 UTC, Kratlis approved these changes

2022-04-08 06:57 UTC, NewerNaigil approved these changes

2022-04-08 06:57 UTC, merged