Task 3958: Written Javadoc for Bottom Navigation, Tabs and App Bar.
jdi-testing/jdi-light pull request #3987
Opened 2022-04-13 15:18 UTC by annav00

2022-04-14 10:21 UTC, rvasilyev requested changes

2022-04-14 10:21 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
>   * https://material-ui.com/components/app-bar/
Коль скоро мы не пишем джавадоки у тестов, это лучше убрать.

2022-04-14 10:21 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/TabsAssert.java
> +     * Checks that switch is disabled.
Здесь точно switch, не tab?

2022-04-14 10:21 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/TabsAssert.java
> +     * Checks that switch is enabled.
Здесь тоже точно switch, не tab?

2022-04-14 10:21 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/BottomNavigation.java
> + * at the bottom of a screen.Each destination is represented by an icon and an optional text label.
Пробел после точки ;)

2022-04-14 10:21 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
> +     * @return {@link JAppBar} annotation instance if present, otherwise {@code null}
Нужен ли здесь этот джавадок? Если да, то метод ничего не возвращает и @return здесь не нужен.

2022-04-14 10:21 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/annotations/JAppBar.java
> + * Annotation for setting custom locators for app bar.
Здесь лучше указать класс через @link, а @see убрать, так как дублирование получается.

2022-04-14 10:30 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
>   * https://material-ui.com/components/app-bar/
убрала

2022-04-14 10:31 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/TabsAssert.java
> +     * Checks that switch is disabled.
Исправила на tab

2022-04-14 10:31 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/TabsAssert.java
> +     * Checks that switch is enabled.
Исправила на tab

2022-04-14 10:31 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/BottomNavigation.java
> + * at the bottom of a screen.Each destination is represented by an icon and an optional text label.
Добавила

2022-04-14 10:35 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
> +     * @return {@link JAppBar} annotation instance if present, otherwise {@code null}
Пожалуй не нужен, потому что при переопределении метода нет каких-то неочевидных моментов. Убрала

2022-04-14 10:37 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/annotations/JAppBar.java
> + * Annotation for setting custom locators for app bar.
Исправила

2022-04-14 15:16 UTC, rvasilyev approved these changes

2022-04-14 15:30 UTC, Kratlis approved these changes

2022-04-15 09:30 UTC, NewerNaigil approved these changes

2022-04-15 09:31 UTC, merged