Task 3989: AppBar refactoring
jdi-testing/jdi-light pull request #3994
Opened 2022-04-19 13:43 UTC by annav00

Needs to add a test to validate the input field. It cannot be completed until [3988](https://github.com/orgs/jdi-testing/projects/1?card_filter_query=assignee%3Aannav00#:~:text=the%20test%20site%20(-,BUG%20%233988,-).) has been completed.

2022-04-20 09:36 UTC, Kratlis requested changes
Обнови описание ПР

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
> +    @UI("(//header[contains(@class, 'MuiAppBar-root')])[2]")
Можно упростить локатор? `.MuiAppBar-root[2]`
Проверь у других элементов на странице, можно ли упростить локаторы. И на других страницах у апп бара

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
> +        prominentMenu.buttonGroup().is().displayed().and().size(3);
Добавить has(): `has().size(3)`

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static Checkbox userIconSwitch;
Можно использовать Switch?

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static AppBar appBarMenu;
Думаю, лучше назвать AppBarWithMenu, чтобы не сложилось впечатление, что это меню

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static AppBar prominentMenu;
Лучше назвать prominentAppBar

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
> +        elevateAppBar.has().classValue(containsString("MuiPaper-elevation0"));
Можно использовать cssClass? `elevateAppBar.has().cssClass("MuiPaper-elevation0");`

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
> +     * Gets buttons.
Можно сказать как-нибудь про button group? Например: Gets button group with buttons in this app bar. 
Тогда в return тоже надо будет поменять

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
>      @JDIAction(value = "Get '{name}' navigation button")
В аннотациях можно убрать value и оставить просто строку?

2022-04-20 09:36 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
> +     * @throws RuntimeException AppBar does not have text field
Не очень понятен этот джавадок. Может, Gets the search field? Тогда надо поменять return, аннотацию и название метода. throws можно убрать, думаю, так как этого нет в коде

2022-04-20 16:20 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
> +    @UI("(//header[contains(@class, 'MuiAppBar-root')])[2]")
Да, исправила

2022-04-20 16:21 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
> +        prominentMenu.buttonGroup().is().displayed().and().size(3);
Добавила

2022-04-20 16:37 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static Checkbox userIconSwitch;
Да, исправила

2022-04-20 16:38 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static AppBar appBarMenu;
Исправила

2022-04-20 16:39 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static AppBar prominentMenu;
Исправила

2022-04-20 16:58 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
> +        elevateAppBar.has().classValue(containsString("MuiPaper-elevation0"));
Да, исправила

2022-04-20 17:02 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
> +     * Gets buttons.
Да, так звучит понятнее. Исправила

2022-04-20 17:03 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
>      @JDIAction(value = "Get '{name}' navigation button")
Да, исправила

2022-04-20 17:09 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
> +     * @throws RuntimeException AppBar does not have text field
В коде нет и поэтому непонятно, когда этот эксепшн возникает или что происходит, если нет этого поля. Мне кажется, наоборот, нужно оставить throws.

С search field согласна, изменила

2022-04-21 10:14 UTC, Kratlis requested changes

2022-04-21 10:14 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
>          simpleAppBarPage.shouldBeOpened();
Зачем в этом тесте проверять все три апп бара. Если проверяется одно и то же у всех, то лучше оставить проверку одного, самого сложного, у которого можно всё проверить

2022-04-21 10:14 UTC, Kratlis commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static AppBar prominentMenu;
Не вижу. Проверь, запушила ли ты эти изменения?

2022-04-21 10:14 UTC, Kratlis commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
> +        prominentMenu.buttonGroup().is().displayed().and().size(3);
Тоже не вижу

2022-04-21 11:03 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/surfaces/AppBar.java
> +     * @throws RuntimeException AppBar does not have text field
Убрала throws

2022-04-21 11:15 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>  public class AppBarPage extends WebPage {
Переименовала

2022-04-21 11:16 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
>          simpleAppBarPage.shouldBeOpened();
Убрала лишние проверки

2022-04-21 11:17 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/surfaces/AppBarTests.java
> +        prominentMenu.buttonGroup().is().displayed().and().size(3);
Сейчас точно есть

2022-04-21 11:18 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static AppBar prominentMenu;
Сейчас точно есть

2022-04-21 11:18 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/BackToTopPage.java
> +    @UI("(//div[contains(@class, 'MuiBox-root')])[1]")
Упростила

2022-04-21 13:45 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static AppBar prominentMenu;
Из-за того, что файл переименован, он отображается как новый созданный, а этот удален, поэтому здесь изменения не отображаются. Нужно в новом файле посмотреть

2022-04-21 13:46 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/surfaces/AppBarPage.java
>      public static AppBar prominentMenu;
Нет, прости, я ошиблась

2022-04-21 13:53 UTC, Kratlis approved these changes

2022-04-22 07:38 UTC, rvasilyev approved these changes

2022-06-15 11:38 UTC, merged