Task 3991: Refactor Snackbar
jdi-testing/jdi-light pull request #3999
Opened 2022-04-21 16:41 UTC by kalimullina

**Snackbar**

- Position() method assert for it are implemented
- hasPosition(Position) method is deleted
- @JDIActionS are corrected

**SnackbarAssert**

@JDIActionS are corrected

**SnackbarPage**

- customizedSnackbar is changed on Alert
- Check names of elements in SnackbarPage

**SnackbarTests**

- customizedSnackbarTest() is deleted
- messageType is moved in successSnackbarTest
- boolean methods with asserts are replaced

Added MessageType enum  for messageType check. Used in successSnackbarTest and messageType() method from Snackbar class

2022-04-25 10:22 UTC, annav00 commented on jdi-light-material-ui-tests/src/main/java/io/github/com/pages/feedback/SnackbarPage.java
> +    @UI("//div[contains(@class, 'MuiSnackbar-root')]//div[@class='MuiSnackbarContent-message']")
`@UI` позволяет комбинировать CSS и XPath локаторы. Можно попробовать упростить локаторы элементов в этом классе. Например, `@UI("div.MuiSnackbar-root div.MuiSnackbarContent-message")`.

2022-04-25 10:51 UTC, annav00 commented
В тесте `simpleSnackbarTest()` проверяется функциональность, которая дальше проверяется и в других тестах. Он точно нужен?

2022-04-26 13:58 UTC, Kratlis requested changes
Джавадок

2022-04-27 10:03 UTC, rvasilyev requested changes

2022-04-27 10:03 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Snackbar.java
> +     * Kinds of message type are error, warning, information, success.
Эту строку я бы убрал, вся информация есть в перечислении.

2022-04-27 10:03 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/feedback/Snackbar.java
> +     * Kinds of position are TOP_RIGHT, TOP_LEFT, TOP_CENTER, BOTTOM_CENTER, BOTTOM_RIGHT, BOTTOM_LEFT.
Здесь тоже лучше убрать эту строку.

2022-04-27 12:40 UTC, Kratlis approved these changes

2022-04-27 14:30 UTC, rvasilyev approved these changes

2022-04-29 14:53 UTC, annav00 approved these changes

2022-06-01 09:57 UTC, merged