Task 3952: Write javadocs for container and grid
jdi-testing/jdi-light pull request #4004
Opened 2022-04-25 15:02 UTC by b14ckster

## Javadoc is written for:
- Container
- ContainerAssert
- Grid
- GridAssert

## Classes are refactored:
- Container
- ContainerTests
- Grid
- GridPage
- GridTests

2022-04-26 09:05 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Container.java
> +    @JDIAction("Check if '{name}' width is fixed")
Аннотация должна быть "Check that '{name}' width is fixed"

2022-04-26 09:12 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Container.java
>      public boolean fixed() {
Если метод возвращет boolean, то название начинаем с is/has. Например, `isFixed`

2022-04-26 10:36 UTC, rvasilyev requested changes

2022-04-26 10:36 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Container.java
> +     * Checks that container has fixed width.
Checks that container has fixed width or not.

2022-04-26 10:36 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Container.java
> +     * Prop fixed is used to design a fixed set of sizes instead of trying to accommodate a fully fluid viewport.
fixed надо взять в кавычки или апострофы, т.к. это название проперти. Не уверен, нужно ли эта строка вообще.

2022-04-26 10:36 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Container.java
> +     * Checks that container has fluid width.
Checks that container has fluid width or not.

2022-04-26 10:36 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Container.java
>      public boolean fluid() {
Здесь по названиию и аннотации как в предыдущем методе.

2022-04-26 10:36 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Container.java
> +     * @return max width as {@link Integer}
Тип возвращаемого значения указан неверно.

2022-04-26 10:36 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Grid.java
> + *
Возможно, этот большой summary стоит разбить на смысловые абзацы для лучшего восприятия.

2022-04-26 10:36 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Grid.java
> +     * Finds a list of grid items.
Gets a list of grid items.

2022-04-26 13:45 UTC, Kratlis requested changes
Можно разбить basicGridItemsTest на два теста?

2022-04-26 13:45 UTC, Kratlis commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/layout/GridAssert.java
> + * Assertions for {@link Grid}
Надо добавить точку

2022-04-28 13:53 UTC, b14ckster commented
##Javadoc is refactored for:
- Container
- ContainerAssert
- Grid
- GridAssert
- HiddenTests

##Classes are refactored for:
- GridTests

2022-04-28 14:48 UTC, Kratlis approved these changes

2022-04-29 10:29 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/layout/HiddenTests.java
> + * @see <a href="https://jdi-testing.github.io/jdi-light/material">MUI test page</a>
Обычно не пишем JavaDoc для класса с тестами

2022-04-29 14:51 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/layout/Grid.java
> + *
Да, лучше <p>

2022-05-04 10:00 UTC, Telelichko commented
@b14ckster,
Среди измененных файлов к этому pull request-у нет HiddenPage и ContainerPage. Нужно ли добавлять javadocs в эти файлы?

2022-05-04 10:24 UTC, annav00 commented
> И есть проблемы с проверкой этой ветки: "Some checks were not successful".

В ветке master_material_ui есть несколько падающих тестов. На них есть задачи на борде

2022-05-04 10:28 UTC, Telelichko commented
> @b14ckster, Среди измененных файлов к этому pull request-у нет HiddenPage и ContainerPage. Нужно ли добавлять javadocs в эти файлы?

Уточнила, не нужно.

2022-05-31 15:31 UTC, merged