Task 3945: Write Javadoc for Checkbox, Menu
jdi-testing/jdi-light pull request #4006
Opened 2022-04-25 16:12 UTC by annav00

2022-04-26 10:07 UTC, rvasilyev requested changes

2022-04-26 10:07 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
> +     * Gets specific item of this menu using its title (full equality is used by searching).
Gets item of this menu matching given name (full equality is used by searching).

2022-04-26 10:07 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
> +     * @param name full text content of the item to be found
@param name expected item name

2022-04-26 10:07 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
>      @JDIAction("Get '{name}' item {0}")
Здесь по аналогии с предыдущим.

2022-04-26 10:07 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
>              .collect(Collectors.toList());
У этого метода забыла джавадок.

2022-04-26 10:07 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
> +     * Scroll menu to the item with given name
Scrolls. Про equality можешь тоже добавить, если там full content

2022-04-26 10:07 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
> +     * @param menuItem full text content of the item to scroll to
@param menuItem expected item name to scroll to

2022-04-26 14:11 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Checkbox.java
> + * Represent Checkbox MUI component on GUI. Checkboxes allow the user to select one or more items from a set.
Represents исправила. the user используется в документации https://mui.com/components/checkboxes

2022-04-26 14:11 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/navigation/MenuAssert.java
> +     * Checks that menu items have given texts
Исправила

2022-04-26 14:12 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
> + * Represent Menu MUI component on GUI. A menu displays a list of choices on a temporary surface.
Represents исправила. the user используется в документации https://mui.com/components/menus/

2022-04-26 14:13 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
>      @JDIAction("Get '{name}' item {0}")
Исправила

2022-04-26 14:15 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
>              .collect(Collectors.toList());
Добавила

2022-04-26 14:20 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
> +     * @param menuItem full text content of the item to scroll to
Исправила

2022-04-27 09:51 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/inputs/Checkbox.java
> + * Represent Checkbox MUI component on GUI. Checkboxes allow the user to select one or more items from a set.
Ok

2022-04-27 09:51 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
> + * Represent Menu MUI component on GUI. A menu displays a list of choices on a temporary surface.
Ok

2022-04-27 10:02 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/navigation/Menu.java
> +     * Gets specific item of this menu using its title (full equality is used by searching).
Исправила

2022-04-27 15:07 UTC, rvasilyev approved these changes

2022-05-04 10:10 UTC, Telelichko commented
@annav00,
нужно ли добавлять javadocs для CheckboxPage?

2022-05-04 10:29 UTC, Telelichko commented
> @annav00, нужно ли добавлять javadocs для CheckboxPage?

Уточнила, не нужно.

2022-05-24 08:06 UTC, merged