Task 3976: Verify Bug 3975 and Refactor Transition
jdi-testing/jdi-light pull request #4011
Opened 2022-04-28 08:11 UTC by annav00

As part of this task, there is a need to write Javadoc, this will be done after the review.

2022-05-04 08:37 UTC, annav00 commented
For information, falling tests in checks are  not related to my task.

2022-05-04 11:28 UTC, rvasilyev requested changes

2022-05-04 11:28 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/utils/TransitionTests.java
>   */
Джавадок у тестов не нужен.

2022-05-04 11:28 UTC, rvasilyev commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/utils/TransitionTests.java
> +        Transition transition = specialTransitionOnThePage(transitionType).get(transitionIndex);
Насколько я вижу, specialTransitionOnThePage() используется единожды. Может вообще его убрать и дата провайдером возвращать нужный список сразу?

2022-05-04 11:28 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/utils/TransitionAssert.java
> +    @JDIAction("Assert that '{name}' is entered")
Вроде, мы для аннотаций использовали Check that?

2022-05-04 11:28 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/Transition.java
> +     * Checks if the transition is entered or not.
Checks that

2022-05-04 11:28 UTC, rvasilyev commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/Transition.java
> +     * Checks if the transition is exited or not.
Checks that

2022-05-05 07:08 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/asserts/utils/TransitionAssert.java
> +    @JDIAction("Assert that '{name}' is entered")
Нет, Assert that

2022-05-05 07:11 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/Transition.java
> +     * Checks if the transition is entered or not.
![image](https://user-images.githubusercontent.com/74856431/166877061-49483351-c4ef-4081-870e-93e9d636bf1a.png)
Checks that в ассертах используем

2022-05-05 07:11 UTC, annav00 commented on jdi-light-material-ui/src/main/java/com/epam/jdi/light/material/elements/utils/Transition.java
> +     * Checks if the transition is exited or not.
![image](https://user-images.githubusercontent.com/74856431/166877061-49483351-c4ef-4081-870e-93e9d636bf1a.png)
Checks that в ассертах используем

2022-05-05 07:15 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/utils/TransitionTests.java
>   */
Убрала

2022-05-05 07:16 UTC, annav00 commented on jdi-light-material-ui-tests/src/test/java/io/github/epam/material/tests/utils/TransitionTests.java
> +        Transition transition = specialTransitionOnThePage(transitionType).get(transitionIndex);
Не подумала об этом, спасибо. Убрала этот метод, изменила датапровайдер и удалила enum для transition, потому что теперь он нигде не используется.

2022-05-06 09:03 UTC, rvasilyev approved these changes

2022-05-26 07:40 UTC, Kchebulaev requested changes

2022-05-26 07:52 UTC, merged