3743 vuetify investigate unstable datatalestests
jdi-testing/jdi-light pull request #4021
Opened 2022-05-19 14:04 UTC by GgStormer

2022-05-19 14:20 UTC, GgStormer commented
Fixed unstable tests: 
slotsTableTest, editDialogTableTest, denseTableTest, customFilterTableTest

2022-05-19 16:45 UTC, GgStormer commented
From logs of runs there are no failed DataTablesTests left.

2022-05-24 08:05 UTC, annav00 requested changes

2022-05-24 12:52 UTC, annav00 approved these changes

2022-07-12 02:00 UTC, closed without merging