3120 - implement Aspect Ratios for Vuetify
jdi-testing/jdi-light pull request #4050
Opened 2022-06-17 07:57 UTC by DucLe8

2022-07-12 01:47 UTC, pnatashap requested changes

2022-07-12 01:47 UTC, pnatashap commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/common/AspectRatios.java
> +    public double ratioValue(double width, double height) {
Method should be static as object data is not used

2022-07-12 01:47 UTC, pnatashap commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/AspectRatiosAssert.java
> +        double epsilon = 0.2d;
0.2 looks like a huge diffence for epsilon. Usually difference in 3 number after . is ok, as it's less then 1% diffence

2022-07-12 02:27 UTC, pnatashap commented
Tests are failed:
[00:32.525] Failed to execute 'AspectRatiosAssert.ratio' for element 'Aspect Ratios Container(css='.v-responsive')' during '10' seconds. 00:32.175 
Expected: a value greater than <1.5733752620545072>
     but: <0.2> was less than <1.5733752620545072>
	at io.github.epam.vuetify.tests.common.AspectRatiosTests.lambda$aspectRatioImageTests$1(AspectRatiosTests.java:30)
	at io.github.epam.vuetify.tests.common.AspectRatiosTests.aspectRatioImageTests(AspectRatiosTests.java:27)

2022-07-14 13:18 UTC, Kchebulaev commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/common/AspectRatiosTests.java
> +        getDriver().manage().window().maximize();
It'd be better to restore window size in `@AfterClass` so it would be done even if test fails

2022-07-21 03:19 UTC, DucLe8 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/AspectRatiosAssert.java
> +    public AspectRatiosAssert ratio(double width, double height) {
removed parameters

2022-07-21 03:21 UTC, DucLe8 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/data/AspectRatiosTestsData.java
> +    public List<AspectRatiosTestDataObject> aspectRatiosTestData() {
comment is added

2022-07-21 08:19 UTC, behhVenn approved these changes

2022-07-22 19:42 UTC, merged