Task3831 button group refactoring
jdi-testing/jdi-light pull request #4074
Opened 2022-07-11 14:55 UTC by MayaElf

2022-07-12 00:21 UTC, pnatashap requested changes

2022-07-12 00:21 UTC, pnatashap commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/VuetifyButtonGroupsTests.java
> +        fontAlignmentGroup.is().selected(4);
порядок выполнения forEach не гарантирован, нет 100% гарантии, что 4 будет выделена последней

2022-07-12 00:21 UTC, pnatashap commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/VuetifyButtonGroupsTests.java
> -        fontDecorationGroupWYSIWYG.getAllButtons().forEach(this::assertSelected);
нужно оставить предыдущую реализацию, читается нормально

2022-07-14 12:04 UTC, closed without merging

2022-07-14 12:04 UTC, MayaElf commented
another one was created