Task 4063: Vuetify Dialog refactoring
jdi-testing/jdi-light pull request #4077
Opened 2022-07-12 12:33 UTC by annav00

Removed all methods that connected to any content in Dialog.
Implemented methods that should be available in Dialog: fullscreen, persistence, get content.

The scroll content method has not been implemented yet.

2022-07-13 02:10 UTC, pnatashap requested changes

2022-07-13 02:10 UTC, pnatashap commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/Dialog.java
> +            core().click(BOTTOM_RIGHT);
зачем этот клик нужен? а если там действие какое-то произойдет и ты на поле ввода попадешь?

2022-07-13 02:51 UTC, pnatashap requested changes

2022-07-13 02:51 UTC, pnatashap commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/Dialog.java
> +        if (!isPersistent()) {
а в случае persistent похоже надо исключение кинуть, что закрыть не можем

2022-07-14 11:55 UTC, annav00 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/Dialog.java
> +            core().click(BOTTOM_RIGHT);
если открыто несколько вложенных окон, то после закрытия одного следующие не закрываются просто так, сначала необходимо сфокусироваться. Заменила на focus()

2022-07-15 04:38 UTC, pnatashap requested changes
Have not chacked the code, as there is a test failure in Dialog tests.
Error:  Tests run: 679, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,217.295 s <<< FAILURE! - in TestSuite
Error:  scrollableDialogTest(io.github.epam.vuetify.tests.complex.DialogTests)  Time elapsed: 3.661 s  <<< FAILURE!
java.lang.AssertionError: 
[43:41.611] Failed to execute 'IsAssert.notVisible' for element 'Radiogroup[19](>css='.v-dialog__content'>xpath='(//div[@role='radiogroup']/child::div)[18]')' during '10' seconds. 43:40.724 
Expected: is "out of the user view"
     but: was "is in the user view"
	at io.github.epam.vuetify.tests.complex.DialogTests.scrollableDialogTest(DialogTests.java:53)
Caused by: java.lang.AssertionError:

2022-08-02 15:25 UTC, vklonin approved these changes

2022-08-02 15:28 UTC, vklonin approved these changes

2022-08-02 15:29 UTC, merged