Vuetify develop wdmfix - test of just adding wait in WebDriver management
jdi-testing/jdi-light pull request #4215
Opened 2022-08-23 06:28 UTC by vklonin

2022-08-24 03:41 UTC, pnatashap requested changes
Нужен PR в master ветку, все страдают!

2022-08-24 03:41 UTC, pnatashap commented on jdi-light-selenium3/src/main/java/com/epam/jdi/light/driver/get/DownloadDriverManager.java
> +                waitAttempts -= 1;
Кажется пропустил обновление driverPath в конце

2022-08-24 09:53 UTC, vklonin commented on jdi-light-selenium3/src/main/java/com/epam/jdi/light/driver/get/DownloadDriverManager.java
> +                waitAttempts -= 1;
Да точно! Поправил.

2023-02-02 03:16 UTC, pnatashap commented
We have fixed this issue in master. Closing

2023-02-02 03:16 UTC, closed without merging