4269 refactor fileinputs
jdi-testing/jdi-light pull request #4474
Opened 2022-11-07 11:43 UTC by Liliya-web

2022-11-07 18:08 UTC, omega790 reviewed
Before review will be done please check test runs and fix failed tests

2022-11-08 07:34 UTC, Liliya-web commented
> Before review will be done please check test runs and fix failed tests

I checked. My tests are not failing. It's some other tests.

2022-11-09 19:25 UTC, omega790 requested changes
Please see the comments

2022-11-09 19:25 UTC, omega790 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/FileInputsTests.java
> +        backgroundColorFileInput.is().clearable();
please add:
backgroundColorFileInput.clearButton().click();

2022-11-09 19:25 UTC, omega790 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/FileInputsTests.java
> +        loadingFileInput.is().reversed();
add notReversed()

2022-11-09 19:25 UTC, omega790 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/FileInputsTests.java
> +        prependIconFileInput.is().rounded();
add notRounded()

2022-11-09 19:25 UTC, omega790 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/FileInputsTests.java
> +
add test for single line

2022-11-10 08:04 UTC, Liliya-web commented on jdi-light-vuetify-tests/src/main/java/io/github/com/pages/FileInputsPage.java
> +    @JDIFileInput(root = "//*[@id='AppendPrependIconFileInput']/div[1]")
I think, itćs more convenient to have better names for elements. And I donćt have to get() required element everytime I need it

2022-11-10 09:06 UTC, Liliya-web commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/FileInputsTests.java
>      public void smallChipsFileInputTest() {
It is not a duplication. First use uploadFiles() and second uploadFile(). I made one test of them

2022-11-10 19:12 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/FileInputAssert.java
>      public FileInputAssert multiple() {
Please use MultipleAssert and delete assert method

2022-11-10 19:12 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/FileInputAssert.java
>                  " to expected suffix text '%s'", actualPrefixText, prefixText));
suffix -> prefix

2022-11-10 19:12 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/FileInputAssert.java
> +    @JDIAction("Assert that '{name}' has detailes hidden")
detailes -> details

2022-11-10 19:12 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/FileInputAssert.java
> +        String actualLoaderHeight = element().getLoaderHeight();
please compare numbers as a numbers, not as strings

2022-11-10 19:12 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/FileInput.java
> +        return finds(".v-input__control .v-label").css("color");
up

2022-11-10 19:26 UTC, omega790 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/FileInputsTests.java
> +        prependInnerIconFileInput.is().singleLine();
+ notSingleLine()

2022-11-10 19:26 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/interfaces/HasMessages.java
> +    default List<String> successMessages() {
Create additional methods with parameters and don't duplicate code

2022-11-10 19:26 UTC, omega790 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/FileInputsTests.java
> +        denseFileInput.is().dense();
+ notDense()

2022-11-10 19:26 UTC, omega790 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/FileInputsTests.java
>      public void complexFileInputTest() {
up

2022-11-14 19:51 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/interfaces/HasMessages.java
> +	@JDIAction("Get '{name}' messages text by locator")
@JDIAction("Get '{name}' messages text by locator") -> @JDIAction("Get '{name}' messages text by locator '{0}'")

2022-11-14 19:51 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/FileInputAssert.java
> +                " is not equal to expected %s", actualLoaderHeight + "px", height + "px"));
`
String.format("Actual element's loader height '%s' is not equal to expected %s", actualLoaderHeight + "px", height + "px")
->
String.format("Actual element's loader height '%s px' is not equal to expected '%s px'", actualLoaderHeight, height)`

2022-11-14 19:51 UTC, omega790 commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/FileInputAssert.java
>                  " to expected suffix text '%s'", actualPrefixText, prefixText));
Please update description

2022-11-14 20:06 UTC, omega790 requested changes

2022-11-16 09:20 UTC, omega790 approved these changes

2022-11-16 09:21 UTC, merged