4232 refactor BottomNavigation
jdi-testing/jdi-light pull request #4578
Opened 2023-01-05 12:22 UTC by Liliya-web

2023-01-09 12:58 UTC, MayaElf requested changes

2023-01-09 12:58 UTC, MayaElf commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/BottomNavigationTests.java
> +    public void measurementsBottomNavigationTest() {
Hi, wrong description :)

2023-01-09 12:58 UTC, MayaElf commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/BottomNavigation.java
> +
Why do you keep here commented code? :)

2023-01-10 07:59 UTC, MayaElf approved these changes

2023-01-10 08:10 UTC, vklonin approved these changes

2023-01-10 08:10 UTC, merged