WIP - 4509 Refactor timepickers check scrollable (to verify CI Test run - do not merge)
jdi-testing/jdi-light pull request #4728
Opened 2023-01-20 12:47 UTC by antonfilichkin

Added test for TimePicker interaction with mouse wheel.
Refactored PO
Temp loggin

2023-01-26 17:32 UTC, MayaElf commented on jdi-light/src/main/java/com/epam/jdi/light/actions/ActionHelper.java
> +    //public static Safe<Boolean> isAssert = new Safe<>(() -> null);
Sorry, a little bit confused, what is your suggestion? line 77 or line 78? :)

2023-01-26 17:34 UTC, MayaElf requested changes

2023-01-26 17:34 UTC, MayaElf commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/TimePicker.java
> +}
Please, add the line otherwise codacy check will be red

2023-01-27 09:25 UTC, EvgeniiKlimenko commented on jdi-light/src/main/java/com/epam/jdi/light/actions/ActionHelper.java
> +    //public static Safe<Boolean> isAssert = new Safe<>(() -> null);
Writing null as a value(and then to DEFAULT variable) leads to null.get() => NPE, as I understand correctly.
Also, In Safe class we have one of the constructors:
public Safe() { this(() -> null); }
Does it have the same problem? And should we remove this NPE-cause constructor from Safe class?

2023-01-31 10:54 UTC, antonfilichkin commented on jdi-light/src/main/java/com/epam/jdi/light/actions/ActionHelper.java
> +    //public static Safe<Boolean> isAssert = new Safe<>(() -> null);
I propose a default constructor - `new Safe<>()` as it will call new `Safe<>(() -> null)` under the hood.

2023-02-07 01:10 UTC, pnatashap commented
PR с именем WIP не подлежат ревью, так как считается, что над ПР еще работает автор. WIP = Work In Progress. 
Если работа закончена, нужно убрать префикс
@antonfilichkin

2023-02-07 01:29 UTC, pnatashap requested changes
Сделай один ПР про timepicker, не понятно, зачем их два, будут конфликты

2023-02-07 01:29 UTC, pnatashap commented on jdi-light/src/main/java/com/epam/jdi/light/actions/ActionHelper.java
> +    //public static Safe<Boolean> isAssert = new Safe<>(() -> null);
ВСЕ пожелания по изменениям в jdi-light делаем НЕ в этой ветке, а отдельным ПР в master и поставить меня в ревьюеры. отсюда изменение УДАЛИТЬ

2023-02-07 01:29 UTC, pnatashap commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/TimePickerAssert.java
> +                    Timer.waitCondition(elem::isClickable);
зачем ассерт после? таймер упадет, что элемент не стал clikable

2023-02-09 11:26 UTC, antonfilichkin commented
Scroll functionality moved to https://github.com/jdi-testing/jdi-light/pull/4765

2023-02-09 11:26 UTC, closed without merging