4716 card reveal refactoring
jdi-testing/jdi-light pull request #4729
Opened 2023-01-23 05:46 UTC by Dr-Java

2023-01-23 15:27 UTC, MayaElf requested changes

2023-01-23 15:27 UTC, MayaElf commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/PaginationTests.java
> +            enabled = false)
Sorry, please, enable as all tests are fixed :)

2023-01-23 15:27 UTC, MayaElf commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/PaginationTests.java
> +            enabled = false)
Sorry, please, enable as all tests are fixed :)

2023-01-23 15:27 UTC, MayaElf commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/PaginationTests.java
> +                "15", "14", "13", "12", "11", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1"
what is this change for :)

2023-01-23 15:27 UTC, MayaElf commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/cards/RevealCard.java
> +    }
why do you choose 'transition' for locator? 'transition' is a very tricky thing)))

2023-01-24 06:08 UTC, Dr-Java commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/PaginationTests.java
> +                "15", "14", "13", "12", "11", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1"
Just formatting)

2023-01-24 11:50 UTC, MayaElf requested changes

2023-01-24 11:50 UTC, MayaElf commented on jdi-light-vuetify-tests/src/main/java/io/github/com/custom/cards/RevealCard.java
> +        return primaryText;
we need to clarify issue with naming concerning using 'get'

2023-01-25 11:32 UTC, MayaElf approved these changes

2023-01-25 12:17 UTC, vklonin approved these changes

2023-01-25 12:17 UTC, merged