Task 4733: Refactor Subheaders Tests
jdi-testing/jdi-light pull request #4734
Opened 2023-01-24 13:11 UTC by sergei820

Descriptions are added to Subheaders tests

2023-01-24 18:04 UTC, MayaElf requested changes

2023-01-25 07:09 UTC, sergei820 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/common/SubheadersTests.java
> +    @Test(description = "Test checks inset Subheader")
Thank you! Fixed all descriptions like this: Test checks inset Subheader features: 'theme' and 'text'
Please, check

2023-01-25 14:52 UTC, MayaElf approved these changes

2023-01-25 14:53 UTC, vklonin approved these changes

2023-01-25 14:53 UTC, merged