4746 Refactor placeholderOverflowButtonTest
jdi-testing/jdi-light pull request #4754
Opened 2023-01-30 06:45 UTC by EvgeniiKlimenko

Change test to use editableOverflowButton, because it allows to remove assigned value and see placeholder text.
So no refresh() is needed now.

2023-02-01 07:48 UTC, MayaElf approved these changes

2023-02-02 03:13 UTC, pnatashap requested changes

2023-02-02 03:13 UTC, pnatashap commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/OverflowButtonsTests.java
> +        editableOverflowButton.has().placeholder("Overflow Btn w/ editable");
Add a logic to select any value

2023-02-02 12:37 UTC, EvgeniiKlimenko commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/OverflowButtonsTests.java
> +        editableOverflowButton.has().placeholder("Overflow Btn w/ editable");
Add logic to select what? I have no selections in this code. What do you mean?

2023-02-07 01:47 UTC, pnatashap requested changes

2023-02-07 01:47 UTC, pnatashap commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/OverflowButtonsTests.java
> +        editableOverflowButton.has().placeholder("Overflow Btn w/ editable");
editableOverflowButton имеет несколько вариантов значений 0, 25, 50, 75 или 100% 
у нас нет нигде логики, которая показывает, как это сделать и проверки установленного значения после установки. а должно быть - это основное назначение элемента

2023-02-07 13:18 UTC, EvgeniiKlimenko commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/OverflowButtonsTests.java
> +        editableOverflowButton.has().placeholder("Overflow Btn w/ editable");
But we have such logic. For example editableOverflowButton() test
editableOverflowButton.sendText("1");
editableOverflowButton.dropDownList().get(1).is().text("100%");

we can assign values to button and check it

2023-02-08 02:14 UTC, pnatashap commented
Requested changed were not made, PR is requested for review with merge conflict.
Merging, will fix it myself

2023-02-08 02:14 UTC, merged