Vuetify develop 4736 refactor bottomsheets overlays
jdi-testing/jdi-light pull request #4761
Opened 2023-02-01 03:14 UTC by marsoloGit

2023-02-01 09:23 UTC, MayaElf approved these changes

2023-02-02 00:52 UTC, pnatashap requested changes

2023-02-02 00:52 UTC, pnatashap commented on jdi-light-vuetify-tests/src/main/java/io/github/com/pages/BottomSheetsPage.java
>  public class BottomSheetsPage extends VuetifyPage {
Сравнила контрол с Dialog и не вижу разницы кроме стиля v-bottom-sheet, т.е. с точки зрения автоматизации тестирования разницы нет.
Еще раз открываем описание, смотрим, если правда разницы нет, то BottomSheet класс удаляем и переписываем тесты на диалог.

2023-02-07 01:33 UTC, pnatashap commented
Элемент удален в другом ПР

2023-02-07 01:33 UTC, closed without merging