Task 4737: Implement additional Calendar tests
jdi-testing/jdi-light pull request #4768
Opened 2023-02-06 08:04 UTC by sergei820

calendarEventRippleTest() done
checkCalendarIntervalWidth() done
calendarWeekdaysTest() done
darkCalendarTest() fixed

2023-02-06 23:58 UTC, pnatashap requested changes

2023-02-06 23:58 UTC, pnatashap commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/CalendarsTests.java
> +        typeDayCalendar.intervalBody().has().css("width", "60px");
не надо одно и то же проверять на всех возможных элементах - у нас задача показать, как проверять разные параметры.
это просто замедляет выполнение и ничего не добавляет по сути

2023-02-06 23:58 UTC, pnatashap commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/CalendarsTests.java
> +        darkCalendar.calendarDays().has().size(4);
один тест на один календарь - так проще и быстрее выполняется

2023-02-06 23:58 UTC, pnatashap commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/CalendarsTests.java
> +        typeWeekCalendar.intervalBody().has().css("width", "60px");
а где проверка содежимого этого intervalBody? отметки тогда надо проверить

2023-02-06 23:58 UTC, pnatashap commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/Calendar.java
> +    public UIElement eventRipple(int eventNumber) {
что это за элемент? он добавлен, но в тестах не участвует - так нельзя

2023-02-10 10:28 UTC, MayaElf approved these changes

2023-02-16 03:57 UTC, merged