4735 refactor tests bottom navigation leftovers
jdi-testing/jdi-light pull request #4772
Opened 2023-02-07 18:13 UTC by antonfilichkin

2023-02-08 02:59 UTC, pnatashap requested changes

2023-02-08 02:59 UTC, pnatashap commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/interfaces/isScrollable.java
> +public interface isScrollable extends ICoreElement {
ну прямо креминал не соблюдать правила именования

2023-02-08 08:58 UTC, MayaElf requested changes

2023-02-08 08:58 UTC, MayaElf commented on jdi-light-vuetify-tests/src/main/java/io/github/com/pages/BottomNavigationPage.java
>      @UI("#growBottomNavigation")
Please, fix codacy issue

2023-02-08 09:39 UTC, antonfilichkin commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/interfaces/isScrollable.java
> +public interface isScrollable extends ICoreElement {
Fixed

2023-02-10 13:40 UTC, MayaElf approved these changes

2023-02-14 09:15 UTC, vklonin approved these changes

2023-02-14 09:15 UTC, merged