Task4739: Add and refactor tests for features of element RangeSlider on a test-site
jdi-testing/jdi-light pull request #4773
Opened 2023-02-08 10:39 UTC by annav00

2023-02-10 14:25 UTC, MayaElf requested changes

2023-02-10 14:25 UTC, MayaElf commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/asserts/RangeSliderAssert.java
> +        return this;
'Element has label?' :)

2023-02-10 14:25 UTC, MayaElf commented on jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/RangeSlider.java
> +        return thumbLabels().get(1).getSize().height;
скобки у метода height? :) или это встроенный селениумовский height?

2023-02-12 18:37 UTC, annav00 commented on jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/complex/RangeSlidersTests.java
> +    }
But we don't use it anywhere else.

2023-02-13 11:53 UTC, MayaElf approved these changes

2023-02-16 03:19 UTC, merged