deleted dark(), light() methods
jdi-testing/jdi-light pull request #4799
Opened 2023-03-09 15:33 UTC by OlgaPoddubnaia

this PR is related to the conversation inside this [PR ](https://github.com/jdi-docs/jdi-light/pull/1353)

2023-03-21 08:37 UTC, vklonin approved these changes

2023-03-22 06:01 UTC, pnatashap commented
в чем причина удаления? ну удобно можно будет проверить, светлая или темная таблица

2023-03-22 06:02 UTC, pnatashap requested changes
я не вижу причин для удаления, вроде были интерфейсы, но тут они не добавлены

2023-03-22 09:28 UTC, OlgaPoddubnaia commented
> я не вижу причин для удаления, вроде были интерфейсы, но тут они не добавлены

интерфейс ThemeAssert<A, T> имплементируется в SimpleTableAssert на 13ой строке

2023-03-22 09:28 UTC, OlgaPoddubnaia commented
> в чем причина удаления? ну удобно можно будет проверить, светлая или темная таблица

в themeAssert есть метод проверки темы. удаление,чтобы не дублировать код

2023-03-22 17:35 UTC, merged