added test descriptions for progress bar
jdi-testing/jdi-light pull request #4998
Opened 2023-06-22 10:02 UTC by FursovaKate

and fix test failures due to the browser size

2023-06-23 19:41 UTC, pnatashap requested changes

2023-06-23 19:41 UTC, pnatashap commented on jdi-light-angular-tests/src/test/resources/test.properties
> +browser.size= 1024x762
мы не будем менять размер окна для всего запуска, будет масса нестабильностей

2023-06-27 08:26 UTC, MayaElf approved these changes

2023-06-29 10:08 UTC, MayaElf requested changes

2023-06-29 10:29 UTC, alla-blinkova commented on jdi-light-angular-tests/src/main/java/io/github/com/StaticSite.java
I guess it should be renamed to `defaultUser`

2023-07-07 04:07 UTC, pnatashap requested changes

2023-07-07 04:07 UTC, pnatashap commented on jdi-light-angular-tests/src/main/java/io/github/com/StaticSite.java
Actually you do not need this User at all, now Angular does not use login from the main site

2023-07-07 04:07 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/ProgressBarUnitTests.java
>          skipForFirefox();
skipForFirefox also should be removed

2023-07-07 04:07 UTC, pnatashap commented on jdi-light-angular-tests/src/test/resources/test.properties
> +element.search.strategy=soft
Why do we need to change it?

2023-07-07 04:07 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/enums/ProgressBarColors.java
> +    RED("mat-warn"),
Why do we keep old values?

2023-07-07 06:10 UTC, merged