4960+4967: tests refactoring BUTTON and implementing class BUTTON
jdi-testing/jdi-light pull request #5034
Opened 2023-08-07 12:46 UTC by b14ckster

2023-08-08 06:37 UTC, vklonin commented on jdi-light-angular-tests/src/main/java/io/github/com/pages/ButtonsPage.java
> +
предлагаю обработать все кнопки в каждой секции
возможно имеет смысл сделать отдельно секции на странице и в каждой секции свою группу кнопок

2023-08-08 06:38 UTC, vklonin commented on jdi-light-angular-tests/src/main/java/io/github/com/pages/ButtonsPage.java
> +public class ButtonsPage extends NewAngularPage {
предлагаю в каждой группе кнопок выделить объект который позволяет проверять результат нажатия на кнопку

2023-08-08 06:49 UTC, vklonin commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/common/ButtonsTests.java
> +
Предлагаю accent, primary, warn назвать типами, а buttonTypes - buttonImplementations потому что например accent используется например в кнопках basic accent disabled etc - но не у всех из них есть свойство color. Судя по всему свойство color зависит от реализации кнопки - можно посмотреть в репозитории сайта - как оно появляется.

2023-08-08 06:51 UTC, vklonin commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Button.java
> +    @JDIAction(value = "Get '{name}' color")
про цвет нужно посмотреть более детально как реально получить цвет кнопки например через палитру.

2023-08-08 06:54 UTC, vklonin commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/enums/buttons/ButtonsTexts.java
> +    BASIC_TEXT("Basic"),
Это реализация на сайте - ее нужно убрать из фреймворка - поскольку в реальности такие тексты на кнопках встречаться не будут скорее всего - все что относится к реализации на тестовом сайте нужно описывать в тестах а не во фреймворке

2023-08-08 07:03 UTC, vklonin commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/common/ButtonsTests.java
> +public class ButtonsTests extends TestsInit {
Тесты предлагаю сгруппировать по группам кнопок
В тестах проверить что кнопка обладает всеми ожидаемыми атрибутами
Проверить что после нажатия меняется надпись в контрольном боксе

можно сделать тестовые методы и переиспользовать их для всех групп кнопок чтобы не дублировать код

2023-08-08 07:24 UTC, vklonin commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/enums/buttons/ButtonsColors.java
> +public enum ButtonsColors {
По цветам предлагаю попробовать получать реальные цвета из палитры если это возможно
По сути это не цвет а название элемента палитры может быть это как то обыграть в названии свойства - что оно возвращает не цвет но название цвета в палитре

2023-08-08 07:27 UTC, vklonin requested changes

2023-08-08 07:27 UTC, vklonin commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/common/ButtonsTests.java
> +
по сути это не цвет а Theme color palette for the component - лучше это как то продемонстрировать пользователю фреймворка

2023-08-11 22:35 UTC, pnatashap requested changes

2023-08-11 22:35 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/ButtonAssert.java
> +        jdiAssert(actualText, Matchers.is(expectedText),
Стандартный текст ошибки от матчера вполне читаем, зачем свой такой же собирать?

2023-08-11 22:35 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/ButtonAssert.java
> +                "is not equal to expected '%b'", actualFocused, true));
expected значение ты знаешь, зачем его в строку вставлять кодом?

2023-08-11 22:35 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/ButtonAssert.java
> +            String.format("Actual element's label text '%s' " +
та же история со стандартной ошибкой

2023-08-11 22:35 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/ButtonAssert.java
> +            String.format("Actual element's color '%s' " +
та же история со стандартной ошибкой

2023-08-11 22:35 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/ButtonAssert.java
> +            String.format("Actual element's visual type '%s' " +
та же история со стандартной ошибкой

2023-08-11 22:35 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Button.java
> +    public String visualTypeOfButton() {
если мы претендуем, что вернем какой-то тип, то надо возвращать тип, но мне кажется OfButton надо из названия убрать, мы и так в классе кнопка.
Ввести допом туда значение undefined и его возвращать, если ничего не нашли, а не null

2023-08-11 22:35 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/ButtonsUnitTests.java
> +        assertTrue(defaultColorButton.defaultColor());
мы не делаем тесты с assertTrue, предлагаю вообще удалить эту папку, все равно все надо проверять

2023-08-11 22:35 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/common/ButtonsTests.java
> +        basicButtons.get(index).shouldBe().displayed();
у нас все тесты тут одинаковые, вот просто под копирку. у нас нет цели сделать прогон тестов непременно часа 4, а то не солидно, давайте рандомные элементы что ли брать и свести все в один тест

2023-08-20 03:30 UTC, merged