4938 ripples tests refactoring
jdi-testing/jdi-light pull request #5040
Opened 2023-08-15 14:36 UTC by MayaElf

2023-09-08 21:11 UTC, pnatashap requested changes
пока мне кажется, что этот элемент должен быть удален ввиду ненужности для автоматизации тестирования

2023-09-08 21:11 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/RippleUnitTests.java
>  public class RippleUnitTests extends TestsInit {
насколько я вижу по другим ПР - unit решили удалить

2023-09-08 21:11 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Ripple.java
> +            int xEndIndex = style.indexOf("px; top:");
а что если top окажется не после стиля с px?

2023-09-08 21:11 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/RippleTests.java
> +
а зачем нам вообще нужен этот элемент для автоматизации тестирования? анимацию проверять - нестабильно, такие проверки правильно на уровень unit-тестов элементов выносить. зачем он нужен вообще?

2023-09-14 08:27 UTC, MayaElf commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/unit/RippleUnitTests.java
>  public class RippleUnitTests extends TestsInit {
удалено

2023-09-14 08:28 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Ripple.java
> +            int xEndIndex = style.indexOf("px; top:");
удалено

2023-09-14 08:28 UTC, MayaElf commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/RippleTests.java
> +
удалено

2023-09-14 20:06 UTC, pnatashap approved these changes

2023-09-15 09:46 UTC, merged