4953+4965: Angular input implementing and refactoring tests
jdi-testing/jdi-light pull request #5058
Opened 2023-08-31 14:11 UTC by b14ckster

2023-09-08 10:46 UTC, vklonin requested changes

2023-09-08 10:46 UTC, vklonin commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Input.java
> +package com.epam.jdi.light.angular.elements.common;
В этот класс предлагаю добавить 
- метод focus() и проверку есть ли фокус на этом input
- метод который проверяет можно ли поле увеличить по вертикали и (в контексте проверки изменяемый ли инпут по высоте или нет можно использовать
and <textarea>)
- метод который изменяет размер поля по вертикали (как поле inputs_basic_comment)
- метод который позволяет управлять скролером сбоку если поле заполнено - можно проиллюстрировать на inputs_basic_comment - добавить в него много строк и используя ползунок справа управлять видимостью содержимого поля
![image](https://github.com/jdi-testing/jdi-light/assets/57947006/0f92126b-4709-4890-979d-b06e39ecb53a)

2023-09-08 10:46 UTC, vklonin commented on jdi-light-angular-tests/src/main/java/io/github/com/pages/InputPage.java
> +    public static Icon suffixForInput;
у этого поля можно проверить наличие иконки

2023-09-08 10:46 UTC, vklonin commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Input.java
> +public class Input extends UIBaseElement<InputAssert> implements IsInput, SetValue, HasLabel {
Предлагаю смотреть на инпут более широко: например элемент inputs_errorStateMatcher_email с проверкой - часть которая работает проверкой мы берем в наш элемент - предлагаю так же брать часть mat-label и тоже отнести ее к Input через метод label() например
![image](https://github.com/jdi-testing/jdi-light/assets/57947006/9c050c24-c03a-470a-907b-e5745ab8c6e5)

2023-09-08 10:46 UTC, vklonin commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Input.java
> +    public String labelText() {
Это как я понимаю невидимый area-label - его как то надо отделить от Label который видимый

2023-09-08 10:46 UTC, vklonin commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Input.java
> +
в контексте проверки изменяемый ли инпут по высоте или нет можно использовать
<input> and <textarea>

2023-09-08 10:50 UTC, vklonin commented
Так же предлагаю подумать какие еще свойства или методы можно добавить для удобства тестирования сайта на котором есть элементы Input

2023-09-08 17:50 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Input.java
> +public class Input extends UIBaseElement<InputAssert> implements IsInput, SetValue, HasLabel {
Мне кажется, что мы можем куда-то не туда залезть, если label и ошибки будем цеплять, мне кажется надо отдельно делать класс для mat-form-field, чтобы его можно было быстро выбирать по имени и передавать, какой именно класс инпутом выступает: Input, TextArea, Checkbox и пр

2023-09-08 18:25 UTC, pnatashap requested changes
В целом, кроме Input нужен именно сложный элемент типа FormField, в котором уже сделать все подписи, кнопочки, префиксы и ошибки валидации
И не надо писать тесты просто для того, чтобы они были

2023-09-08 18:25 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/enums/InputsTypes.java
> +            .orElse(UNDEFINED);
по-умолчанию инпут имеет тип text

2023-09-08 18:25 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Input.java
> +    public String labelText() {
area-label - это про accessibility и в обычной автоматизации его никто не будет проверять, поэтому предлаю вообще убрать, для такого тестирования обычно отдельные тулы используются и точечно затыкать какие-то проверки сейчас смысла не вижу

2023-09-11 04:47 UTC, vklonin commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/common/InputTests.java
> +        inputBasicFood.has().value("Ice");
потому что там contains

2023-12-21 09:12 UTC, vklonin approved these changes

2023-12-21 09:14 UTC, merged