4911-refactoringRadioButtonTests
jdi-testing/jdi-light pull request #5087
Opened 2023-10-02 09:44 UTC by MayaElf

2023-10-24 01:37 UTC, pnatashap requested changes
Only the control was checked

2023-10-24 01:37 UTC, pnatashap commented on jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/complex/RadioButtons.java
> +                                                     .setUIElementName(LABEL);
мы не трогаем никакой проект, кроме ангуляра

2023-10-24 01:37 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +public class RadioButtons extends UIListBase<UISelectAssert<RadioButtonsAssert, RadioButtons>> {
Согласно наименованиям angular это называется RadioGroup, мы всегда сохраняем имена
RadioButton - отдельный элемент со своими свойствами, именно их список мы должны уметь возвращать

2023-10-24 01:37 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
>      @JDIAction("'{name}' radio button  contain value '{0}'")
комментарий не соответствует возвращаемому значению

2023-10-24 01:37 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
>      public void click(String value) {
мы должны уметь выделять и снимать выделение с элемента, не только кликать по нему.
еще полезно уметь выделять не одно значение, а несколько из списка

2023-10-24 01:37 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +    public AngularColors color(String value) {
цвет - свойство отдельного элемента, вот туда и надо его вынести

2023-10-24 01:37 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +        if (getRadioButtonByTagValue(value).hasClass("mat-warn")) {
каждый раз вызывать поиск элемента - очень плохо, элемент нужно получать один раз

2023-10-24 01:37 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +        return core().attr("aria-label").equalsIgnoreCase(ariaLabel);
тоже самое с area-label, как в предыдущем ПР

2023-10-24 01:37 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +        return core().attr("labelposition").equalsIgnoreCase("before");
свойство может стоять на группе (или не стоять) и отдельно у каждого radio может быть переопределено, это половина решения, получается

2023-10-24 13:54 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
>      @JDIAction("'{name}' radio button  contain value '{0}'")
исправила

2023-10-24 13:55 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +        if (getRadioButtonByTagValue(value).hasClass("mat-warn")) {
исправила

2023-10-24 13:55 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +        return core().attr("aria-label").equalsIgnoreCase(ariaLabel);
удалила

2023-10-25 10:00 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
>      public void click(String value) {
Добрый день,
- у радио баттон нет check\uncheck, только click
- у радио баттон нет multiple-choice варианта, выбранный вариант только один

2023-10-25 10:03 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +    public AngularColors color(String value) {
у нас в других реализациях (смотрела bootstrap и material-ui) тоже сделано только через группу, нет отдельного элемента кнопки.
вы предлагаете в ангуляре сделать отдельную реализацию для кнопки, правильно понимаю комментарий?

2023-10-25 10:15 UTC, MayaElf commented on jdi-light-bootstrap/src/main/java/com/epam/jdi/light/ui/bootstrap/elements/complex/RadioButtons.java
> +                                                     .setUIElementName(LABEL);
исправила

2023-10-25 11:12 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioButtons.java
> +        return core().attr("labelposition").equalsIgnoreCase("before");
добавила

2023-10-26 02:08 UTC, pnatashap requested changes
Предыдущий комментарий не понят

2023-10-26 02:08 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioGroup.java
> +    @JDIAction("'{name}'is required")
```suggestion
    @JDIAction("'{name}' is required")
```

2023-10-26 02:08 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioGroup.java
> +    private UIElement getRadioButtonByTagValue(String value) {
Метод должен быть public, так же должен быть метод, который получает весь список RadioButton.

Допустим, нам нужно сделать проверки для всех элементов в RadioGroup, мы должны иметь возможность получить список и прогнать. Если мы каждый раз будем получать по имени, это будет крайне медленно.
Помимо того, что сейчас у нас нет возможности проверить, какие опции нам туда подсунули.
Я в предыдущем ревью написала, что нам нужен класс для описания группы и для описания каждого отдельного RadioButton

2023-10-26 02:08 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/RadioButtonsAssert.java
> +public class RadioButtonsAssert extends UISelectAssert<RadioButtonsAssert, RadioGroup> {
Раз мы переименовали в RadioButton, и этот класс тоже должен был следом переименоваться

2023-10-26 02:08 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/RadioButtonTests.java
>      @BeforeMethod
В предыдущем ПР уже писала про BeforeMethod

2023-10-26 02:16 UTC, pnatashap commented
Первый попавшийся пример для vue https://github.com/jdi-testing/jdi-light/blob/angular_rework_development/jdi-light-vuetify/src/main/java/com/epam/jdi/light/vuetify/elements/complex/radiobuttons/RadioButtons.java

2023-10-26 11:06 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioGroup.java
> +    @JDIAction("'{name}'is required")
проставила пробелы

2023-10-26 11:10 UTC, MayaElf commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/RadioButtonTests.java
>      @BeforeMethod
заменила

2023-10-26 11:12 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/RadioButtonsAssert.java
> +public class RadioButtonsAssert extends UISelectAssert<RadioButtonsAssert, RadioGroup> {
заменила

2023-10-26 11:14 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioGroup.java
> +    private UIElement getRadioButtonByTagValue(String value) {
1) public + аннтоция проставлены
2) у нас есть реализованный метод getRadioButtons(), как раз используем его для получения кнопки по имени.
@JDIAction("Get radio button by tag value {0}")
    public UIElement getRadioButtonByTagValue(String value) {
        UIElement element = null;
        for (UIElement e : **getRadioButtons()**) {
            if (e.find("input").attr("value").equalsIgnoreCase(value)) {
                element = e;
            }
        }
        return element;
    }

2023-10-27 22:27 UTC, pnatashap requested changes
Я так и не вижу класса для описания RadioButton и его проверок, как в указанном примере

2023-10-27 22:27 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/RadioGroup.java
> +    @JDIAction("'{name}' radio button  contain value '{0}'")
комментарий не соответствует функции

2023-11-02 21:13 UTC, pnatashap requested changes
Тесты не смотрела, только контролы

2023-11-02 21:13 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +    private static final String INPUT_SELECTION_CONTROL = "//input[@type='radio']";
```suggestion
    private static final String INPUT_SELECTION_CONTROL = ".//input[@type='radio']";
```

2023-11-02 21:13 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +    public boolean isRadioButtonBeforePosition() {
```suggestion
    public boolean hasBeforePosition() {
```

2023-11-02 21:13 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +        return attr("labelposition").equalsIgnoreCase("before");
Метод даст неправильный результат  для "Radio group label position before 1" и "Radio group label position before 2" с тестового сайта

2023-11-02 21:13 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +            return AngularColors.ACCENT;
Для отдельной кнопки если значение не задано в нем самом, оно определено для всей группы

2023-11-02 21:13 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +        getRadioButtonByValue(value).find(By.cssSelector(".mdc-form-field")).click();
а почему мы просто не можем по кнопке и кликнуть?

2023-11-02 21:13 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isChecked(String value) {
1. почему такого метода нет у RadioButton? это же его информация
2. где метод для получения выбранного?

2023-11-02 21:13 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.find("input").attr("value").equalsIgnoreCase(value)) {
а почему у RadioButton нет метода по получению его подписи?

2023-11-06 21:29 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +    private static final String INPUT_SELECTION_CONTROL = "//input[@type='radio']";
поправила

2023-11-06 21:32 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +    public boolean isRadioButtonBeforePosition() {
поправила

2023-11-06 21:40 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +        getRadioButtonByValue(value).find(By.cssSelector(".mdc-form-field")).click();
когда в вертикальной группе кнопка большого размера (как у нас на сайте ), он кликает в середину и не происходит выделения радио батон. клик есть, а выделения нет.

2023-11-06 21:47 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.find("input").attr("value").equalsIgnoreCase(value)) {
добавила

2023-11-07 12:15 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isChecked(String value) {
добавила

2023-11-07 12:39 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +        return attr("labelposition").equalsIgnoreCase("before");
исправила

2023-11-07 13:46 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +            return AngularColors.ACCENT;
пересмотрела все наши реализации, цвета на уровне группы нет ни в одной. поэтому, извините, не соображу, как взять цвет с уровня группы

2023-11-08 03:29 UTC, pnatashap requested changes

2023-11-08 03:29 UTC, pnatashap commented on config/checkstyle/checkstyle.xml
> +    <property name="lineSeparator" value="lf_cr_crlf"/>
этот стиль используется в нескольких проектах, если мы его изменим тут, оно потом может сломать после вливания, ПР на стиль должен быть отдельным ПР в master вместе с исправлением всех файлов, которые этому условию не удовлетворяют

2023-11-08 03:29 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +            return AngularColors.ACCENT;
ну значит пиши комментарий в коде и задачу на сайт, чтобы это можно было проверить

2023-11-08 03:29 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +        getRadioButtonByValue(value).find(By.cssSelector(".mdc-form-field")).click();
так у нас клик переопределен, как такое может быть?

2023-11-08 03:29 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isChecked(String value) {
а почему не используется?

2023-11-08 03:29 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.find("input").attr("value").equalsIgnoreCase(value)) {
а почему не используется?

2023-11-08 03:29 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.hasClass("mat-mdc-radio-checked")) {
у кнопки есть метод, который отдает значение, выделен он или нет, почему не использовать его?

2023-11-08 03:29 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +        find(By.cssSelector(".mdc-form-field")).click();
локатор частично дублируется с 42 строкой

2023-11-08 12:27 UTC, MayaElf commented on config/checkstyle/checkstyle.xml
> +    <property name="lineSeparator" value="lf_cr_crlf"/>
спасибо, откатила изменения в этом пиаре, сделала отдельный

2023-11-09 12:22 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isChecked(String value) {
добавила в тест

2023-11-09 12:33 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.find("input").attr("value").equalsIgnoreCase(value)) {
добавила тест

2023-11-09 12:55 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.hasClass("mat-mdc-radio-checked")) {
исправила

2023-11-09 13:01 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +        find(By.cssSelector(".mdc-form-field")).click();
вынесла в константу

2023-11-10 10:22 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +            return AngularColors.ACCENT;
спасибо, исправила

2023-11-10 10:29 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +        getRadioButtonByValue(value).find(By.cssSelector(".mdc-form-field")).click();
Долго разбиралась, если честно, почему падают тесты. Думала, что это из-за ngModel реализации. А потом перебором вариантов нашла, что  лефтэреа клик выделяет. Добавила указание на форм-филд тесты перестали падать. Предполагаю, что даже при переопределении вертикальные кнопки оказываются слишком большие. Если убрать find(By.cssSelector(".mdc-form-field")) , то все тесты на вертикальные радио кнопки падают, клик есть, выделения нет :( Для горизонтальных кнопок все работает без find(By.cssSelector(".mdc-form-field"))

2023-11-14 01:36 UTC, pnatashap requested changes
conflicts after changes in styles

2023-11-15 02:20 UTC, pnatashap requested changes

2023-11-15 02:20 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +        getRadioButtonByValue(value).find(By.cssSelector(".mdc-form-field")).click();
1 Кликать по mdc-form-field не безопасно, не все части приводят к выделению, надо кликать по mdc-radio
2 Любая такая проблема не повод оставлять непонятный код внутри другого класса

2023-11-15 02:20 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isChecked(String value) {
не вижу где

2023-11-15 02:20 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.find("input").attr("value").equalsIgnoreCase(value)) {
не вижу

2023-11-15 02:20 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +                radioButton = e;
а почему мы отсюда не возвращаем значение?

2023-11-15 13:38 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +        getRadioButtonByValue(value).find(By.cssSelector(".mdc-form-field")).click();
исправила

2023-11-15 13:43 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isChecked(String value) {
1) по checked
 @Test(description = "Test verifies value and the radio-button is checked")
    public void basicRadioButtonsTest() {
        basicRadioGroup.show();
        basicRadioGroup.is().displayed();
        basicRadioGroup.click("2");
        basicRadioGroup.click("1");
        basicRadioGroup.click("2");
        basicRadioGroup.is().checked("2");
        basicRadioGroup.is().notChecked("1");
        basicRadioGroup.radioButtons().get(1).is().checked();
        basicRadioGroup.radioButtons().get(0).is().notChecked();
    }
2) получение выбранного
 @Test(description = "Test verifies that there is checked radio-button in the group")
    public void getCheckedRadioButtonTest() {
        colorRadioGroup.has().checkedRadioButton();
        requiredRadioGroup.has().noCheckedRadioButton();
    }

2023-11-15 13:45 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.find("input").attr("value").equalsIgnoreCase(value)) {
@Test(description = "Test verifies radio button label")
    public void radioButtonLabelTest() {
        requiredRadioGroup.radioButtons().get(0).has().label("One");
    }

2023-11-15 13:53 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +                radioButton = e;
45 строка вернет либо чекнутую радиобатон, либо нулл. оба случая покрыты
@JDIAction("Get '{name}' checked radio-button")
    public RadioButton getCheckedRadioButton() {
        RadioButton radioButton = null;
        for (RadioButton e : radioButtons()) {
            if (e.isChecked()) {
                radioButton = e;
            }
        }
        return radioButton;
    }

2023-11-16 00:36 UTC, pnatashap requested changes

2023-11-16 00:36 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isChecked(String value) {
1. Еще раз перечитай первый вопрос
2. Посмотри на вот эту строку кода https://github.com/jdi-testing/jdi-light/pull/5087/files#diff-278ebeb52c9d2a302e5401e2a7c09a8bbdfea63f44f2c823a1c391e1b0ef7ccdR60
3. Исправь ошибку

2023-11-16 00:36 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +                radioButton = e;
У тебя есть RadioGroup из 50 пунктов, ты переберешь их все, потом только что-то вернешь, хотя знаешь, что выделенным элементом может быть только один. Как исправить проблему длительного выполнения?

2023-11-16 00:36 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +            if (e.find("input").attr("value").equalsIgnoreCase(value)) {
Речь про полное нарушение инкапсуляции, ты залазишь в дочерний элемент, что-то оттуда берешь и считаешь, что это нормально. 
Мы можем захотеть работать с элементами по label, можем по value.

2023-11-16 00:57 UTC, pnatashap requested changes

2023-11-16 00:57 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/radiobuttons/RadioGroupAssert.java
> +            "There is checked radio button in the group");
Ну правильнее написать, что именно выделено, а не просто что что-то выделено, отлаживать же надо, что было

2023-11-16 00:57 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +    public boolean isDisabled() {
Если мы переопределили isDisabled, то логично и isEnabled переопределить, чтобы быстрее работал

2023-11-16 00:57 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isDisabled() {
Тоже должна быть аннотация Override и надо переопределить isEnabled

2023-11-16 09:50 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +                radioButton = e;
заменено на стрим

2023-11-16 10:06 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioButton.java
> +    public boolean isDisabled() {
добавлено

2023-11-16 10:06 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/radiobuttons/RadioGroup.java
> +    public boolean isDisabled() {
добавлено

2023-11-19 03:44 UTC, merged

2023-11-19 03:44 UTC, pnatashap commented
исправления зашли в тупик, все исправила сама