4914_cardTestsRefRebased
jdi-testing/jdi-light pull request #5231
Opened 2023-11-24 09:28 UTC by MayaElf

2023-12-01 15:12 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/CardTests.java
>          card.getButtonByText("LIKE").has().cssClass("cdk-focused");
Это специальный класс для определения фокуса?

2023-12-01 15:12 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/CardTests.java
> +        cardAlignEndActions.is().alignEndActions();
```suggestion
        cardAlignEndActions.has().alignEndActions();
```

2023-12-01 15:13 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/CardTests.java
> +        cardAlignStartActions.is().aligStartActions();
```suggestion
        cardAlignStartActions.has().aligStartActions();
```

2023-12-02 01:42 UTC, pnatashap requested changes

2023-12-02 01:42 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        return this.find("//img");
Картинка может быть в заголовке и содержимом, этот метод будет что-то возвращать любое.
Правильнее явно сделать заголовок и содержимое отдельными классами и у каждого получать картинку

2023-12-02 01:42 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        return this.finds("//button");
кнопки могут быть в заголовке, в тексте в действиях, неправильно работать с ними со всеми 
https://material.angular.io/components/card/examples - можно открыть редактор и проверять в онлайне

`<mat-card class="example-card">
  <mat-card-header>
    <mat-card-title>Shiba Inu</mat-card-title>
    <mat-card-subtitle>Dog Breed</mat-card-subtitle>
    <button mat-button>LIKE</button>
  </mat-card-header>
  <mat-card-content>
    <p>This card indeterminates progress bar.</p>
    <p>{{longText}}</p>
    <button mat-button>LIKE</button>
  </mat-card-content>
  <mat-card-actions>
    <button mat-button>LIKE</button>
    <button mat-button>SHARE</button>
  </mat-card-actions>
</mat-card>`

2023-12-08 08:44 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        return this.finds("//button");
может быть, добавить в примеры Кард с кнопками в заголовке?

2023-12-08 08:45 UTC, MayaElf commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/complex/CardTests.java
>          card.getButtonByText("LIKE").has().cssClass("cdk-focused");
да, для фокуса

2023-12-08 08:55 UTC, MayaElf commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
>      @JDIAction("Get '{name}' text")
тогда раделю на два, для заголовка и тела. нужен ответ на вопрос, который чуть ниже, можно ли сделать в одном классе, или все-таки делать отдельные классы. спасибо

2024-01-09 12:48 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        return this.find("//img");
@pnatashap  почему правильнее разбивать картинки на те что в заголовке и в содержимом ? Мы же в тестах идем от карты `card.has()...` а не от внутренностей карты

2024-01-09 19:19 UTC, pnatashap requested changes

2024-01-09 19:19 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        return this.finds("//button");
кнопка может находится где угодно и мы об этом не узнаем, наша задача возвращать только кнопки из actions и НЕ брать никакие другие

2024-01-09 19:19 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public UIElement getAvatar() {
у аватара есть класс

2024-01-09 19:19 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public boolean hasImage() {
произвольная картинка нам не нужна

2024-01-09 19:19 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw new RuntimeException("Element doesn't have image");
runtime exception мы кидаем по-другому

2024-01-10 10:11 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        return this.find("//img");
@pnatashap  
> Правильнее явно сделать заголовок и содержимое отдельными классами и у каждого получать картинку
Как ты это видишь ? Отдельные классы HeaderCardImage и ContentCardImage на ровне с классами angular элементов com.epam.jdi.light.angular.elements ?

2024-01-12 00:48 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        return this.find("//img");
1. Зачем отдельные классы для картинок? Чем оно отличается от обычного img? 
2. https://material.angular.io/components/card/overview#basic-card-sections вот тут описана вся структура, которая может быть у карточки, вот эту структуру и должны читать и отдавать. но когда пишем локаторы, понимаем, что простые элементы могут быть где угодно, поэтому локатор должен быть адекватным
3. не все части, описанные в документации, обязательно должны быть, это надо иметь ввиду

2024-01-12 10:40 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public UIElement getAvatar() {
класс Avatar я нашел в другом модуле io.github.com.custom;
Из него не импортируется

2024-01-12 10:46 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public boolean hasImage() {
Убрал этот метод

2024-01-12 10:48 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw new RuntimeException("Element doesn't have image");
Пример в другом классе почти такой же 

![image](https://github.com/jdi-testing/jdi-light/assets/152188803/abb7a123-7a02-4bb7-a1a3-81b66fae4a91)

2024-01-12 10:48 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw new RuntimeException("Element doesn't have image");
Изменил

2024-01-12 18:47 UTC, pnatashap requested changes
конфликт слияния, ни одна автопроверка не проверена

2024-01-15 19:04 UTC, pnatashap requested changes
Продумай структуру основного компонента, а потом пиши под него код.
Текущий ПР практически полностью переписывать надо

2024-01-15 19:04 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
>      public WebList getButtons() {
почитай документацию по наименованиям методов, про это там корректно написано

2024-01-15 19:04 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//mat-card-header//img");
а почему есть метод, который даст размер первой попавшейся картинки заголока? а просто картинку получить нельзя?

2024-01-15 19:04 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//img");
зачем нам метод который получает размер первой попавшейся картинки из карты, но саму картинку получить нельзя?

2024-01-15 19:49 UTC, pnatashap requested changes

2024-01-15 19:49 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        if (image.hasClass("mat-mdc-card-xl-image")) {
есть метод, который позволяет найти класс по регулярному выражению, используй его.

2024-01-17 09:46 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//mat-card-header//img");
Не понимаю, что значит "просто" картинку ?

2024-01-17 09:46 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//img");
Не понимаю, что значит "просто" картинку ?

2024-01-17 23:16 UTC, pnatashap requested changes

2024-01-17 23:16 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//img");
Получить Image, чтобы проверить url, alt, размер в пикселях. мы не только размер должны проверять

2024-01-17 23:16 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//mat-card-header//img");
Получить Image, чтобы проверить url, alt, размер в пикселях. мы не только размер должны проверять

2024-01-17 23:16 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            return new Image().setCore(Image.class, core().find("//img"));
1. повторяющийся локатор
2. уже несколько раз писала, что в карточке картинок может быть много, согласно документации в структуре описана только одна, вот локатор до нее мы и должны использовать

2024-01-17 23:16 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public UIElement getAvatar() {
подумала, что есть, как в остальных фреймворках
все равно, открываем описание класса на сайте ангуляра:
`<img mat-card-avatar> - An image used as an avatar within the header`
Это не UIElement, это Image!

2024-01-18 09:36 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//mat-card-header//img");
Для проверки url, alt есть отдельный тест `attributeCardTest()`, там проверка этих атрибутов только для одной картинки. Хочешь ли ты сказать что url, alt и еще размер в пикселях нужно проверять для каждой картинки ?

В задаче, по которой этот ПР сделан, https://github.com/jdi-testing/jdi-light/issues/4914 
не написано про url, alt и размер в пикселях. Можешь ли ты отредактировать задачу так как считаешь нужным ?

2024-01-18 09:36 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//img");
https://github.com/jdi-testing/jdi-light/issues/4914

2024-01-18 10:46 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public UIElement getAvatar() {
Поменял на Image

2024-01-18 11:44 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        if (image.hasClass("mat-mdc-card-xl-image")) {
Исправил

2024-01-18 19:23 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement image = core().find("//mat-card-header//img");
1. При чем тут тесты? Описание элемента еще не готово, я тесты не смотрела даже
2. Бывает картинка в заголовке - аватар, бывает картинка в карточке - это другая картинка. Причем обе могут быть, а могут не быть (в этом ревью уже много комментариев по этому поводу). Если мы тестируем как выглядит страничка, то мы должны уметь проверять все эти компоненты и не только по тем размерам (которые быть вообще не обязаны), но и все, что мы обычно с картинкой делаем - альтернативный текст проверить, url, размеры, все что угодно. НЕ НАДО делать на все это отдельные методы валидации, потому что они уже есть у класса Image и проверены в html пакете

2024-01-19 10:58 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            return new Image().setCore(Image.class, core().find("//img"));
`find("//img[" + imageNumber + "]")`

2024-01-19 22:27 UTC, pnatashap requested changes

2024-01-22 09:24 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public Image image(int imageNumber) {
ну просто раньше ты писала что нужен метод, возвращающий конкретную картинку. 
Специального id у картинки нет. Как тогда нужно захватывать картинку ?

2024-01-22 09:51 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw new RuntimeException("Element does not have actions");
ок

2024-01-22 10:11 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public Image getAvatar() {
ок

2024-01-22 10:12 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public UIElement getFooter() {
ок

2024-01-22 10:20 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
>      public UIElement getSubtitle() {
ok

2024-01-22 10:20 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
>      public UIElement getHeader() {
ok

2024-01-22 11:16 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        core().show();
ok

2024-01-23 08:14 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public Image image(int imageNumber) {
![image](https://github.com/jdi-testing/jdi-light/assets/152188803/c1664639-6ad6-4235-a828-f9ac1f4720c9)
Картинка находится не в теле, а непосредственно в карточке

2024-01-24 14:36 UTC, pnatashap requested changes

2024-01-25 14:09 UTC, spbqaru commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public Image image(int imageNumber) {
> 1. в чем вопрос?
> 2. а локатор у тебя в коде на что указывает?

Наталья, ты имеешь ввиду что локатор //img  слишком универсальный?
тогда нужно взять картинку из структуры карточки mat-card>img прямой наследник от mat-card
чтобы исключить вероятность взять картинку из header.

и метод надо переназвать в cardBodyImage  по аналогии с cartHeaderImage?

2024-01-29 19:45 UTC, pnatashap requested changes

2024-01-29 19:45 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement potentialImage = core().find("//mat-card-header//img");
```suggestion
        UIElement potentialImage = core().find(".//mat-card-header//img");
```

2024-01-29 19:45 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement potentialImage = core().find("//img[@mat-card-image]");
```suggestion
        UIElement potentialImage = core().find(".//img[@mat-card-image]");
```

2024-01-29 19:45 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw runtimeException("Element doesn't have image", this);
не надо тут кидать исключение, мы возвращаем элемент, далее у него можно проверить, жив ли он

2024-01-29 19:45 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw runtimeException("Element does not have actions");
а где метод для всех проверить, есть ли actions?

2024-01-29 19:45 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public Button getButtonByText(String text) {
и здесь тоже, убрать  get из названия, как и соседних методов

2024-01-29 19:45 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/CardAssert.java
> +        jdiAssert(element().cardBodyImage().height(), Matchers.equalTo(height), "HEIGHT IS DIFFERENT");
1. Зачем capslock сообщение об ошибке?
2. Сообщение об ошибке вообще не информативно, не понятно сколько по факту, сколько ждали
3. Зачем вообще кастомное сообщение?

2024-01-29 20:17 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public Image image(int imageNumber) {
зачем методы в карточке называть card**** ??? мы и так в ней, зачем еще раз писать?

2024-01-30 09:31 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw runtimeException("Element doesn't have image", this);
Не понимаю, что значит "жив" ? в этом методе мы хотим получить картинку. Если её нет, то что мы дальше можем проверять ?

2024-01-30 09:35 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw runtimeException("Element does not have actions");
Для всех карт сразу проверить, есть ли класс mat-mdc-card-actions-align-end ? Зачем ?

2024-01-30 09:35 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public Button getButtonByText(String text) {
убрал

2024-01-30 09:37 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/CardAssert.java
> +        jdiAssert(element().cardBodyImage().height(), Matchers.equalTo(height), "HEIGHT IS DIFFERENT");
1. Делал по аналогии с другими методами в этом классе.
2. Разве jdiAssert не выводит ожидаемое и по факту значения ?
3. Делал по аналогии с предыдущими методами в этом классе.

2024-01-30 09:38 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement potentialImage = core().find("//mat-card-header//img");
изменил

2024-01-30 09:38 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement potentialImage = core().find("//img[@mat-card-image]");
изменил

2024-01-30 11:04 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public Image image(int imageNumber) {
убрали card***

2024-01-30 11:32 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/CardAssert.java
> +        jdiAssert(element().cardBodyImage().height(), Matchers.equalTo(height), "HEIGHT IS DIFFERENT");
Убрал кастомные сообщения

2024-01-31 00:28 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +            throw runtimeException("Element does not have actions");
для всех пользователей пакета

2024-01-31 00:36 UTC, pnatashap requested changes

2024-01-31 00:36 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/CardAssert.java
> +        jdiAssert(actualCardImageSize, Matchers.is(size));
зачем actualCardImageSize запрашивать отдельно?

2024-01-31 16:23 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
>      @JDIAction("Get '{name}' text")
бесполезный метод, удалить

2024-01-31 16:24 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement e = core().find("mat-card-actions");
есть метод cardActions для получения этого объекта, не надо дублировать код

2024-01-31 16:25 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +    public CardImageSize cardHeaderImageSize() {
а почему есть метод только размера картинки в заголовке?

2024-02-01 14:06 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/complex/Card.java
> +        UIElement e = core().find("mat-card-actions");
использовал

2024-02-01 14:06 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/CardAssert.java
> +                "Card actions are in end align position");
исправил

2024-02-29 10:59 UTC, closed without merging

2024-02-29 11:00 UTC, igor-vlasiuk commented
because of rework