[WIP] 4941 test refactoring divider element
jdi-testing/jdi-light pull request #5241
Opened 2023-12-01 09:11 UTC by igor-vlasiuk

https://github.com/jdi-testing/jdi-light/issues/4941

2023-12-02 01:47 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerSeparatorAssert.java
> +        jdiAssert(element().isHorizontal() ? "is horizontal" : "is not horizontal", Matchers.is("is horizontal"));
не надо проверять строки, сравниваем bool и пишем сообщение, которое будет отображаться в случае ошибки

2023-12-04 08:57 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerSeparatorAssert.java
> +        jdiAssert(element().isHorizontal() ? "is horizontal" : "is not horizontal", Matchers.is("is horizontal"));
поменял

2023-12-06 18:54 UTC, pnatashap requested changes

2023-12-06 18:54 UTC, pnatashap commented on jdi-light-angular-tests/src/main/java/io/github/com/pages/DividerPage.java
> +    public static UIElement textWithDefaultDividers;
- Локатор очень странный и нестабильный
- UIElement используем в самом крайнем случае, если тип не подобрать, а нам кликнуть по нему только. Если это группа элементов и не описывается обычными элементами - значит создаем кастомный элемент в тестовом фреймворке

2023-12-06 18:54 UTC, pnatashap commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/common/DividerTests.java
>      @BeforeMethod(alwaysRun = true)
Делаем один метод, который перед сьютом запускается, если нужно именно перед методом запускать - пишем комментарий зачем оно надо

2023-12-06 18:54 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerSeparatorAssert.java
> +        jdiAssert(element().isHorizontal(), Matchers.is(true), "Default divider separator is not horizontal");
```suggestion
        jdiAssert(element().isHorizontal(), Matchers.is(true), "Divider separator is not horizontal");
```

2023-12-06 18:54 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerSeparatorAssert.java
> +        jdiAssert(element().isVertical(), Matchers.is(true), "Vertical divider separator is not vertical");
```suggestion
        jdiAssert(element().isVertical(), Matchers.is(true), "Divider separator is not vertical");
```

2023-12-06 18:54 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerSeparatorAssert.java
> +        jdiAssert(element().hasInset(), Matchers.is(true), "Inset divider separator doesn't have inset");
```suggestion
        jdiAssert(element().hasInset(), Matchers.is(true), "Divider separator doesn't have inset");
```

2023-12-06 18:54 UTC, pnatashap commented on jdi-light-angular-tests/src/main/java/io/github/com/pages/DividerPage.java
> +    public static JList<Divider> defaultDividersList;
Локатор указывает на list-item, разделители идут следом, явно ошибка в описании страницы

2023-12-06 18:54 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/DividerSeparator.java
> +public class DividerSeparator extends UIBaseElement<DividerSeparatorAssert> {
Не нашла такой сущности, везде вижу только Divider

2023-12-07 09:44 UTC, igor-vlasiuk commented on jdi-light-angular-tests/src/main/java/io/github/com/pages/DividerPage.java
> +    public static JList<Divider> defaultDividersList;
удалил

2023-12-07 09:44 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/DividerSeparator.java
> +public class DividerSeparator extends UIBaseElement<DividerSeparatorAssert> {
удалил этот класс

2023-12-07 17:19 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerAssert.java
> +        jdiAssert(element().isVertical(), Matchers.is(true), "Vertical divider is not vertical");
```suggestion
        jdiAssert(element().isVertical(), Matchers.is(true), "Divider is not vertical");
```

2023-12-08 08:59 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerSeparatorAssert.java
> +        jdiAssert(element().isHorizontal(), Matchers.is(true), "Default divider separator is not horizontal");
изменил

2023-12-08 09:00 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerSeparatorAssert.java
> +        jdiAssert(element().isVertical(), Matchers.is(true), "Vertical divider separator is not vertical");
изменил

2023-12-08 09:00 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerSeparatorAssert.java
> +        jdiAssert(element().hasInset(), Matchers.is(true), "Inset divider separator doesn't have inset");
изменил

2023-12-09 01:20 UTC, pnatashap requested changes

2023-12-09 18:06 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerAssert.java
> +        jdiAssert(element().isHorizontal(), Matchers.is(true), "Default divider is not horizontal");
![image](https://github.com/jdi-testing/jdi-light/assets/152188803/8414e740-a3e0-468b-b381-67026061c413)
не знаю, локально вот как ты предлагаешь

2023-12-09 18:06 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerAssert.java
> +        jdiAssert(element().hasInset(), Matchers.is(true), "Inset divider doesn't have inset");
то же и здесь

2023-12-09 18:07 UTC, igor-vlasiuk commented on jdi-light-angular-tests/src/test/java/io/github/epam/angular/tests/elements/common/DividerTests.java
> +        defaultDividers.waitFor().displayed();
тут была проблема именно с этим тестом, нестабильность. Без этого ожидания коллекция эл-ов была равна 0.

2023-12-09 18:08 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/DividerAssert.java
> +        jdiAssert(element().isVertical(), Matchers.is(true), "Vertical divider is not vertical");
локально сообщение  "Divider is not vertical"

2023-12-11 05:00 UTC, pnatashap approved these changes

2023-12-18 08:43 UTC, MayaElf approved these changes

2023-12-18 09:11 UTC, merged