Task 4934: Refactor Slide Toggle tests
jdi-testing/jdi-light pull request #5243
Opened 2023-12-01 10:11 UTC by ilya1032

Some tests for task 4934

Our test site requires some changes:

Add slide toggle with 'labelPosition' = before

2023-12-19 04:53 UTC, pnatashap requested changes
Merge conflict

2023-12-21 09:37 UTC, vklonin approved these changes

2023-12-21 12:11 UTC, merged

2023-12-21 15:58 UTC, pnatashap reviewed
Should be fixed

2023-12-21 15:58 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +        UIElement e = find("//button");
core().find надо вызывать

2023-12-21 15:58 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +        return hasClass("mat-checked") || hasClass("mat-mdc-slide-toggle-checked");
core().hasClass

2023-12-21 15:58 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +        return core().find(FORM_FIELD_LOCATOR).hasClass("mdc-form-field--align-end");
а как label получить? и в тестах нигде не проверяется текст

2023-12-21 15:58 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +            core().find(FORM_FIELD_LOCATOR).click();
кликать правильнее по кнопке, а не по полю, кто его знает, что в label засунули

2023-12-21 15:58 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +    @JDIAction("'{name}' element label is in before position")
Get if ....

2023-12-22 11:14 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +        UIElement e = find("//button");
ок

2023-12-22 11:15 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +        return hasClass("mat-checked") || hasClass("mat-mdc-slide-toggle-checked");
ок

2023-12-25 11:43 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +    @JDIAction("'{name}' element label is in before position")
Добавил

2023-12-25 11:44 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +            core().find(FORM_FIELD_LOCATOR).click();
изменил

2023-12-25 12:59 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +        return core().find(FORM_FIELD_LOCATOR).hasClass("mdc-form-field--align-end");
текст теперь проверяется 
resultSlideToggle.has().correctLabelsSlideToggleText();

2023-12-25 15:09 UTC, pnatashap reviewed
не вижу изменений

2023-12-25 15:09 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +        return core().find(FORM_FIELD_LOCATOR).hasClass("mdc-form-field--align-end");
так проверяется выравнивание, я про сам текст, который в этом лейбле, бывают случаи, когда он динамический и мы должны иметь возможность его прочитать и проверить, что он такой, какой мы ожидаем

2023-12-25 15:09 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +        return hasClass("mat-checked") || hasClass("mat-mdc-slide-toggle-checked");
не вижу