Task 4934 refactor toggle slide tests
jdi-testing/jdi-light pull request #5282
Opened 2023-12-27 12:43 UTC by igor-vlasiuk

2023-12-27 15:28 UTC, pnatashap requested changes

2023-12-27 15:28 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +        jdiAssert(element().getLabelsSlideToggleText(), Matchers.is("Slide me!"),
Ты правда думаешь, что текст Slide Me достоин быть вшит в библиотеку и другие тексты мы считаем недопустимыми?

2023-12-27 15:28 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +    public String getLabelsSlideToggleText() {
Есть чудесный интерфейс https://github.com/jdi-testing/jdi-light/blob/master/jdi-light-core/src/main/java/com/epam/jdi/light/elements/interfaces/base/HasLabel.java очень хорошо, когда все единообразно

2023-12-27 15:44 UTC, pnatashap requested changes

2023-12-27 15:44 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +                "Slide toggle label has incorrect text");
Стандартный текст ошибки матчера при сравнении строк понятен, а этот не дает никакого понимания, что не так

2024-01-02 13:06 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +        jdiAssert(element().getLabelsSlideToggleText(), Matchers.is("Slide me!"),
Убрал в тесты

2024-01-02 13:48 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +    public String getLabelsSlideToggleText() {
![image](https://github.com/jdi-testing/jdi-light/assets/152188803/7b5b2eab-9f76-4f03-97f4-e6af19c555f4)
не находится label

2024-01-03 11:37 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +                "Slide toggle label has incorrect text");
убрал этот текст

2024-01-03 11:37 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +        jdiAssert(element().getLabelsSlideToggleText(), Matchers.is("Slide me!"),
убрал в тесты

2024-01-04 15:07 UTC, pnatashap requested changes

2024-01-04 15:07 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +        jdiAssert(element().getLabelsSlideToggleText(), Matchers.is("Slide me!"),
не вижу никаких изменений

2024-01-04 15:07 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +                "Slide toggle label has incorrect text");
все еще тут

2024-01-04 15:07 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
> +    public String getLabelsSlideToggleText() {
а override зачем придумали?

2024-01-04 17:23 UTC, pnatashap requested changes

2024-01-04 17:23 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +    public SlideToggleAssert labelsSlideToggleText(String labelsText) {
```suggestion
    public SlideToggleAssert label(String labelText) {
```

2024-01-04 17:23 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
>      public void check() {
@JDIAction должен быть у методов

2024-01-05 10:12 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/asserts/SlideToggleAssert.java
> +    public SlideToggleAssert labelsSlideToggleText(String labelsText) {
поменял

2024-01-05 10:12 UTC, igor-vlasiuk commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
>      public void check() {
убрал

2024-01-05 16:58 UTC, pnatashap requested changes

2024-01-05 16:58 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/SlideToggle.java
>      public void check() {
надо было добавить

2024-01-09 00:00 UTC, pnatashap requested changes

2024-01-09 00:00 UTC, pnatashap approved these changes

2024-01-09 08:28 UTC, merged