rework Angular element: Button
jdi-testing/jdi-light pull request #5407
Opened 2024-03-14 13:03 UTC by spbqaru

rework Angular element: Button

2024-03-14 21:26 UTC, pnatashap requested changes

2024-03-14 21:26 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Button.java
> +    public String color() {
есть интерфейс HasColor

2024-03-14 21:26 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Button.java
> +            return AngularColors.fromName(core().attr("color"))
мы в результате выдаем строку, абсолютно не факт, что у нас в списке будут все варианты, надо просто значение атрибута вернуть и все

2024-03-14 21:26 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Button.java
> +        return !core().finds(ICON_LOCATOR)
зачем двойное отрицание? 
```suggestion
        return core().finds(ICON_LOCATOR).isExist();
```

2024-03-14 21:26 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/interfaces/HasLink.java
> +public interface HasLink extends ICoreElement {
неплохой интерфейс, надо его в core унести (отдельным PR)

2024-03-18 06:32 UTC, vklonin approved these changes

2024-03-18 13:23 UTC, spbqaru commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Button.java
> +    public String color() {
fixed

2024-03-18 13:23 UTC, spbqaru commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/common/Button.java
> +            return AngularColors.fromName(core().attr("color"))
fixed

2024-03-19 00:56 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/interfaces/HasLink.java
> +public interface HasLink extends ICoreElement {
а как оно resolved?

2024-03-26 04:14 UTC, pnatashap requested changes

2024-03-26 04:14 UTC, pnatashap commented on jdi-light-angular/src/main/java/com/epam/jdi/light/angular/elements/interfaces/HasLink.java
> +public interface HasLink extends ICoreElement {
HasLink занесла в core, удалите этот, перенесите на использование интерфейса из core

2024-03-26 13:49 UTC, pnatashap approved these changes

2024-03-27 14:38 UTC, merged